package apps.fis.repository.model;

import java.util.ArrayList;
import java.util.List;

public class FsJzfPaymentItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public FsJzfPaymentItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillidIsNull() {
            addCriterion("BILLID is null");
            return (Criteria) this;
        }

        public Criteria andBillidIsNotNull() {
            addCriterion("BILLID is not null");
            return (Criteria) this;
        }

        public Criteria andBillidEqualTo(String value) {
            addCriterion("BILLID =", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotEqualTo(String value) {
            addCriterion("BILLID <>", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThan(String value) {
            addCriterion("BILLID >", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThanOrEqualTo(String value) {
            addCriterion("BILLID >=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThan(String value) {
            addCriterion("BILLID <", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThanOrEqualTo(String value) {
            addCriterion("BILLID <=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLike(String value) {
            addCriterion("BILLID like", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotLike(String value) {
            addCriterion("BILLID not like", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidIn(List<String> values) {
            addCriterion("BILLID in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotIn(List<String> values) {
            addCriterion("BILLID not in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidBetween(String value1, String value2) {
            addCriterion("BILLID between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotBetween(String value1, String value2) {
            addCriterion("BILLID not between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andMainidIsNull() {
            addCriterion("MAINID is null");
            return (Criteria) this;
        }

        public Criteria andMainidIsNotNull() {
            addCriterion("MAINID is not null");
            return (Criteria) this;
        }

        public Criteria andMainidEqualTo(String value) {
            addCriterion("MAINID =", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidNotEqualTo(String value) {
            addCriterion("MAINID <>", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidGreaterThan(String value) {
            addCriterion("MAINID >", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidGreaterThanOrEqualTo(String value) {
            addCriterion("MAINID >=", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidLessThan(String value) {
            addCriterion("MAINID <", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidLessThanOrEqualTo(String value) {
            addCriterion("MAINID <=", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidLike(String value) {
            addCriterion("MAINID like", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidNotLike(String value) {
            addCriterion("MAINID not like", value, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidIn(List<String> values) {
            addCriterion("MAINID in", values, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidNotIn(List<String> values) {
            addCriterion("MAINID not in", values, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidBetween(String value1, String value2) {
            addCriterion("MAINID between", value1, value2, "mainid");
            return (Criteria) this;
        }

        public Criteria andMainidNotBetween(String value1, String value2) {
            addCriterion("MAINID not between", value1, value2, "mainid");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeIsNull() {
            addCriterion("NONTAXPROGRAMCODE is null");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeIsNotNull() {
            addCriterion("NONTAXPROGRAMCODE is not null");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeEqualTo(String value) {
            addCriterion("NONTAXPROGRAMCODE =", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeNotEqualTo(String value) {
            addCriterion("NONTAXPROGRAMCODE <>", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeGreaterThan(String value) {
            addCriterion("NONTAXPROGRAMCODE >", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeGreaterThanOrEqualTo(String value) {
            addCriterion("NONTAXPROGRAMCODE >=", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeLessThan(String value) {
            addCriterion("NONTAXPROGRAMCODE <", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeLessThanOrEqualTo(String value) {
            addCriterion("NONTAXPROGRAMCODE <=", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeLike(String value) {
            addCriterion("NONTAXPROGRAMCODE like", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeNotLike(String value) {
            addCriterion("NONTAXPROGRAMCODE not like", value, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeIn(List<String> values) {
            addCriterion("NONTAXPROGRAMCODE in", values, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeNotIn(List<String> values) {
            addCriterion("NONTAXPROGRAMCODE not in", values, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeBetween(String value1, String value2) {
            addCriterion("NONTAXPROGRAMCODE between", value1, value2, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramcodeNotBetween(String value1, String value2) {
            addCriterion("NONTAXPROGRAMCODE not between", value1, value2, "nontaxprogramcode");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameIsNull() {
            addCriterion("NONTAXPROGRAMNAME is null");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameIsNotNull() {
            addCriterion("NONTAXPROGRAMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameEqualTo(String value) {
            addCriterion("NONTAXPROGRAMNAME =", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameNotEqualTo(String value) {
            addCriterion("NONTAXPROGRAMNAME <>", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameGreaterThan(String value) {
            addCriterion("NONTAXPROGRAMNAME >", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameGreaterThanOrEqualTo(String value) {
            addCriterion("NONTAXPROGRAMNAME >=", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameLessThan(String value) {
            addCriterion("NONTAXPROGRAMNAME <", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameLessThanOrEqualTo(String value) {
            addCriterion("NONTAXPROGRAMNAME <=", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameLike(String value) {
            addCriterion("NONTAXPROGRAMNAME like", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameNotLike(String value) {
            addCriterion("NONTAXPROGRAMNAME not like", value, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameIn(List<String> values) {
            addCriterion("NONTAXPROGRAMNAME in", values, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameNotIn(List<String> values) {
            addCriterion("NONTAXPROGRAMNAME not in", values, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameBetween(String value1, String value2) {
            addCriterion("NONTAXPROGRAMNAME between", value1, value2, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andNontaxprogramnameNotBetween(String value1, String value2) {
            addCriterion("NONTAXPROGRAMNAME not between", value1, value2, "nontaxprogramname");
            return (Criteria) this;
        }

        public Criteria andUnitsIsNull() {
            addCriterion("UNITS is null");
            return (Criteria) this;
        }

        public Criteria andUnitsIsNotNull() {
            addCriterion("UNITS is not null");
            return (Criteria) this;
        }

        public Criteria andUnitsEqualTo(String value) {
            addCriterion("UNITS =", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsNotEqualTo(String value) {
            addCriterion("UNITS <>", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsGreaterThan(String value) {
            addCriterion("UNITS >", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsGreaterThanOrEqualTo(String value) {
            addCriterion("UNITS >=", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsLessThan(String value) {
            addCriterion("UNITS <", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsLessThanOrEqualTo(String value) {
            addCriterion("UNITS <=", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsLike(String value) {
            addCriterion("UNITS like", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsNotLike(String value) {
            addCriterion("UNITS not like", value, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsIn(List<String> values) {
            addCriterion("UNITS in", values, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsNotIn(List<String> values) {
            addCriterion("UNITS not in", values, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsBetween(String value1, String value2) {
            addCriterion("UNITS between", value1, value2, "units");
            return (Criteria) this;
        }

        public Criteria andUnitsNotBetween(String value1, String value2) {
            addCriterion("UNITS not between", value1, value2, "units");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(String value) {
            addCriterion("AMOUNT =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(String value) {
            addCriterion("AMOUNT <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(String value) {
            addCriterion("AMOUNT >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(String value) {
            addCriterion("AMOUNT >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(String value) {
            addCriterion("AMOUNT <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(String value) {
            addCriterion("AMOUNT <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLike(String value) {
            addCriterion("AMOUNT like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotLike(String value) {
            addCriterion("AMOUNT not like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<String> values) {
            addCriterion("AMOUNT in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<String> values) {
            addCriterion("AMOUNT not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(String value1, String value2) {
            addCriterion("AMOUNT between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(String value1, String value2) {
            addCriterion("AMOUNT not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeIsNull() {
            addCriterion("STANDARDKINDCODE is null");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeIsNotNull() {
            addCriterion("STANDARDKINDCODE is not null");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeEqualTo(String value) {
            addCriterion("STANDARDKINDCODE =", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeNotEqualTo(String value) {
            addCriterion("STANDARDKINDCODE <>", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeGreaterThan(String value) {
            addCriterion("STANDARDKINDCODE >", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeGreaterThanOrEqualTo(String value) {
            addCriterion("STANDARDKINDCODE >=", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeLessThan(String value) {
            addCriterion("STANDARDKINDCODE <", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeLessThanOrEqualTo(String value) {
            addCriterion("STANDARDKINDCODE <=", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeLike(String value) {
            addCriterion("STANDARDKINDCODE like", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeNotLike(String value) {
            addCriterion("STANDARDKINDCODE not like", value, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeIn(List<String> values) {
            addCriterion("STANDARDKINDCODE in", values, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeNotIn(List<String> values) {
            addCriterion("STANDARDKINDCODE not in", values, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeBetween(String value1, String value2) {
            addCriterion("STANDARDKINDCODE between", value1, value2, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindcodeNotBetween(String value1, String value2) {
            addCriterion("STANDARDKINDCODE not between", value1, value2, "standardkindcode");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameIsNull() {
            addCriterion("STANDARDKINDNAME is null");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameIsNotNull() {
            addCriterion("STANDARDKINDNAME is not null");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameEqualTo(String value) {
            addCriterion("STANDARDKINDNAME =", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameNotEqualTo(String value) {
            addCriterion("STANDARDKINDNAME <>", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameGreaterThan(String value) {
            addCriterion("STANDARDKINDNAME >", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameGreaterThanOrEqualTo(String value) {
            addCriterion("STANDARDKINDNAME >=", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameLessThan(String value) {
            addCriterion("STANDARDKINDNAME <", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameLessThanOrEqualTo(String value) {
            addCriterion("STANDARDKINDNAME <=", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameLike(String value) {
            addCriterion("STANDARDKINDNAME like", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameNotLike(String value) {
            addCriterion("STANDARDKINDNAME not like", value, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameIn(List<String> values) {
            addCriterion("STANDARDKINDNAME in", values, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameNotIn(List<String> values) {
            addCriterion("STANDARDKINDNAME not in", values, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameBetween(String value1, String value2) {
            addCriterion("STANDARDKINDNAME between", value1, value2, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andStandardkindnameNotBetween(String value1, String value2) {
            addCriterion("STANDARDKINDNAME not between", value1, value2, "standardkindname");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(String value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(String value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(String value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(String value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(String value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(String value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLike(String value) {
            addCriterion("AMT like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotLike(String value) {
            addCriterion("AMT not like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<String> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<String> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(String value1, String value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(String value1, String value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andBanknumIsNull() {
            addCriterion("BANKNUM is null");
            return (Criteria) this;
        }

        public Criteria andBanknumIsNotNull() {
            addCriterion("BANKNUM is not null");
            return (Criteria) this;
        }

        public Criteria andBanknumEqualTo(String value) {
            addCriterion("BANKNUM =", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotEqualTo(String value) {
            addCriterion("BANKNUM <>", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumGreaterThan(String value) {
            addCriterion("BANKNUM >", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumGreaterThanOrEqualTo(String value) {
            addCriterion("BANKNUM >=", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLessThan(String value) {
            addCriterion("BANKNUM <", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLessThanOrEqualTo(String value) {
            addCriterion("BANKNUM <=", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLike(String value) {
            addCriterion("BANKNUM like", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotLike(String value) {
            addCriterion("BANKNUM not like", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumIn(List<String> values) {
            addCriterion("BANKNUM in", values, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotIn(List<String> values) {
            addCriterion("BANKNUM not in", values, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumBetween(String value1, String value2) {
            addCriterion("BANKNUM between", value1, value2, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotBetween(String value1, String value2) {
            addCriterion("BANKNUM not between", value1, value2, "banknum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 02 17:31:10 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Sep 02 17:31:10 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}