package apps.fis.repository.dao;

import apps.fis.repository.model.FsQdfSysCtl;
import apps.fis.repository.model.FsQdfSysCtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsQdfSysCtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    int countByExample(FsQdfSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    int deleteByExample(FsQdfSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    int insert(FsQdfSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    int insertSelective(FsQdfSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    List<FsQdfSysCtl> selectByExample(FsQdfSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfSysCtl record, @Param("example") FsQdfSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SYS_CTL
     *
     * @mbggenerated Thu Jul 11 14:33:44 CST 2013
     */
    int updateByExample(@Param("record") FsQdfSysCtl record, @Param("example") FsQdfSysCtlExample example);
}