package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfBaseBank;
import apps.fisjz.repository.model.FsJzfBaseBankExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface FsJzfBaseBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int countByExample(FsJzfBaseBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByExample(FsJzfBaseBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insert(FsJzfBaseBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insertSelective(FsJzfBaseBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    List<FsJzfBaseBank> selectByExample(FsJzfBaseBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    FsJzfBaseBank selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfBaseBank record, @Param("example") FsJzfBaseBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExample(@Param("record") FsJzfBaseBank record, @Param("example") FsJzfBaseBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfBaseBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BANK
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKey(FsJzfBaseBank record);
}