package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfBaseFunc;
import apps.fisjz.repository.model.FsJzfBaseFuncExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsJzfBaseFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int countByExample(FsJzfBaseFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByExample(FsJzfBaseFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insert(FsJzfBaseFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insertSelective(FsJzfBaseFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    List<FsJzfBaseFunc> selectByExample(FsJzfBaseFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    FsJzfBaseFunc selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfBaseFunc record, @Param("example") FsJzfBaseFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExample(@Param("record") FsJzfBaseFunc record, @Param("example") FsJzfBaseFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfBaseFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_FUNC
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKey(FsJzfBaseFunc record);
}