package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfActTxn;
import apps.fisjz.repository.model.FsJzfActTxnExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsJzfActTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int countByExample(FsJzfActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByExample(FsJzfActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insert(FsJzfActTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insertSelective(FsJzfActTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    List<FsJzfActTxn> selectByExample(FsJzfActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    FsJzfActTxn selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfActTxn record, @Param("example") FsJzfActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExample(@Param("record") FsJzfActTxn record, @Param("example") FsJzfActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfActTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKey(FsJzfActTxn record);
}