package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfPaymentItem;
import apps.fisjz.repository.model.FsJzfPaymentItemExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsJzfPaymentItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int countByExample(FsJzfPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByExample(FsJzfPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insert(FsJzfPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insertSelective(FsJzfPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    List<FsJzfPaymentItem> selectByExample(FsJzfPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    FsJzfPaymentItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfPaymentItem record, @Param("example") FsJzfPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExample(@Param("record") FsJzfPaymentItem record, @Param("example") FsJzfPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_ITEM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKey(FsJzfPaymentItem record);
}