package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfBaseBdgagency;
import apps.fisjz.repository.model.FsJzfBaseBdgagencyExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsJzfBaseBdgagencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int countByExample(FsJzfBaseBdgagencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByExample(FsJzfBaseBdgagencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insert(FsJzfBaseBdgagency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insertSelective(FsJzfBaseBdgagency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    List<FsJzfBaseBdgagency> selectByExample(FsJzfBaseBdgagencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    FsJzfBaseBdgagency selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfBaseBdgagency record, @Param("example") FsJzfBaseBdgagencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExample(@Param("record") FsJzfBaseBdgagency record, @Param("example") FsJzfBaseBdgagencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfBaseBdgagency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_BDGAGENCY
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKey(FsJzfBaseBdgagency record);
}