package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfBaseNontax;
import apps.fisjz.repository.model.FsJzfBaseNontaxExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsJzfBaseNontaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int countByExample(FsJzfBaseNontaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByExample(FsJzfBaseNontaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insert(FsJzfBaseNontax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insertSelective(FsJzfBaseNontax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    List<FsJzfBaseNontax> selectByExample(FsJzfBaseNontaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    FsJzfBaseNontax selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfBaseNontax record, @Param("example") FsJzfBaseNontaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExample(@Param("record") FsJzfBaseNontax record, @Param("example") FsJzfBaseNontaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfBaseNontax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_NONTAX
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKey(FsJzfBaseNontax record);
}