package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsJzfBaseStorageid;
import apps.fisjz.repository.model.FsJzfBaseStorageidExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsJzfBaseStorageidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int countByExample(FsJzfBaseStorageidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByExample(FsJzfBaseStorageidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insert(FsJzfBaseStorageid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int insertSelective(FsJzfBaseStorageid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    List<FsJzfBaseStorageid> selectByExample(FsJzfBaseStorageidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    FsJzfBaseStorageid selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsJzfBaseStorageid record, @Param("example") FsJzfBaseStorageidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByExample(@Param("record") FsJzfBaseStorageid record, @Param("example") FsJzfBaseStorageidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKeySelective(FsJzfBaseStorageid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_BASE_STORAGEID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    int updateByPrimaryKey(FsJzfBaseStorageid record);
}