package apps.fisjz.repository.dao;

import apps.fisjz.repository.model.FsSysAreaConfig;
import apps.fisjz.repository.model.FsSysAreaConfigExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FsSysAreaConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int countByExample(FsSysAreaConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByExample(FsSysAreaConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int deleteByPrimaryKey(String areaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insert(FsSysAreaConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int insertSelective(FsSysAreaConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    List<FsSysAreaConfig> selectByExample(FsSysAreaConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    FsSysAreaConfig selectByPrimaryKey(String areaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsSysAreaConfig record, @Param("example") FsSysAreaConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByExample(@Param("record") FsSysAreaConfig record, @Param("example") FsSysAreaConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKeySelective(FsSysAreaConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_SYS_AREA_CONFIG
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    int updateByPrimaryKey(FsSysAreaConfig record);
}