package apps.fisjz.repository.model;

import java.util.ArrayList;
import java.util.List;

public class FsJzfActTxnExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public FsJzfActTxnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBanknumIsNull() {
            addCriterion("BANKNUM is null");
            return (Criteria) this;
        }

        public Criteria andBanknumIsNotNull() {
            addCriterion("BANKNUM is not null");
            return (Criteria) this;
        }

        public Criteria andBanknumEqualTo(String value) {
            addCriterion("BANKNUM =", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotEqualTo(String value) {
            addCriterion("BANKNUM <>", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumGreaterThan(String value) {
            addCriterion("BANKNUM >", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumGreaterThanOrEqualTo(String value) {
            addCriterion("BANKNUM >=", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLessThan(String value) {
            addCriterion("BANKNUM <", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLessThanOrEqualTo(String value) {
            addCriterion("BANKNUM <=", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLike(String value) {
            addCriterion("BANKNUM like", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotLike(String value) {
            addCriterion("BANKNUM not like", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumIn(List<String> values) {
            addCriterion("BANKNUM in", values, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotIn(List<String> values) {
            addCriterion("BANKNUM not in", values, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumBetween(String value1, String value2) {
            addCriterion("BANKNUM between", value1, value2, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotBetween(String value1, String value2) {
            addCriterion("BANKNUM not between", value1, value2, "banknum");
            return (Criteria) this;
        }

        public Criteria andBillidIsNull() {
            addCriterion("BILLID is null");
            return (Criteria) this;
        }

        public Criteria andBillidIsNotNull() {
            addCriterion("BILLID is not null");
            return (Criteria) this;
        }

        public Criteria andBillidEqualTo(String value) {
            addCriterion("BILLID =", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotEqualTo(String value) {
            addCriterion("BILLID <>", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThan(String value) {
            addCriterion("BILLID >", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThanOrEqualTo(String value) {
            addCriterion("BILLID >=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThan(String value) {
            addCriterion("BILLID <", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThanOrEqualTo(String value) {
            addCriterion("BILLID <=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLike(String value) {
            addCriterion("BILLID like", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotLike(String value) {
            addCriterion("BILLID not like", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidIn(List<String> values) {
            addCriterion("BILLID in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotIn(List<String> values) {
            addCriterion("BILLID not in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidBetween(String value1, String value2) {
            addCriterion("BILLID between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotBetween(String value1, String value2) {
            addCriterion("BILLID not between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIsNull() {
            addCriterion("PAYNOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIsNotNull() {
            addCriterion("PAYNOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeEqualTo(String value) {
            addCriterion("PAYNOTESCODE =", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotEqualTo(String value) {
            addCriterion("PAYNOTESCODE <>", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeGreaterThan(String value) {
            addCriterion("PAYNOTESCODE >", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYNOTESCODE >=", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLessThan(String value) {
            addCriterion("PAYNOTESCODE <", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLessThanOrEqualTo(String value) {
            addCriterion("PAYNOTESCODE <=", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLike(String value) {
            addCriterion("PAYNOTESCODE like", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotLike(String value) {
            addCriterion("PAYNOTESCODE not like", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIn(List<String> values) {
            addCriterion("PAYNOTESCODE in", values, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotIn(List<String> values) {
            addCriterion("PAYNOTESCODE not in", values, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeBetween(String value1, String value2) {
            addCriterion("PAYNOTESCODE between", value1, value2, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotBetween(String value1, String value2) {
            addCriterion("PAYNOTESCODE not between", value1, value2, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeIsNull() {
            addCriterion("NOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andNotescodeIsNotNull() {
            addCriterion("NOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andNotescodeEqualTo(String value) {
            addCriterion("NOTESCODE =", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotEqualTo(String value) {
            addCriterion("NOTESCODE <>", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeGreaterThan(String value) {
            addCriterion("NOTESCODE >", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTESCODE >=", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeLessThan(String value) {
            addCriterion("NOTESCODE <", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeLessThanOrEqualTo(String value) {
            addCriterion("NOTESCODE <=", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeLike(String value) {
            addCriterion("NOTESCODE like", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotLike(String value) {
            addCriterion("NOTESCODE not like", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeIn(List<String> values) {
            addCriterion("NOTESCODE in", values, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotIn(List<String> values) {
            addCriterion("NOTESCODE not in", values, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeBetween(String value1, String value2) {
            addCriterion("NOTESCODE between", value1, value2, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotBetween(String value1, String value2) {
            addCriterion("NOTESCODE not between", value1, value2, "notescode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIsNull() {
            addCriterion("CHECKCODE is null");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIsNotNull() {
            addCriterion("CHECKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckcodeEqualTo(String value) {
            addCriterion("CHECKCODE =", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotEqualTo(String value) {
            addCriterion("CHECKCODE <>", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeGreaterThan(String value) {
            addCriterion("CHECKCODE >", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKCODE >=", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLessThan(String value) {
            addCriterion("CHECKCODE <", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLessThanOrEqualTo(String value) {
            addCriterion("CHECKCODE <=", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLike(String value) {
            addCriterion("CHECKCODE like", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotLike(String value) {
            addCriterion("CHECKCODE not like", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIn(List<String> values) {
            addCriterion("CHECKCODE in", values, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotIn(List<String> values) {
            addCriterion("CHECKCODE not in", values, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeBetween(String value1, String value2) {
            addCriterion("CHECKCODE between", value1, value2, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotBetween(String value1, String value2) {
            addCriterion("CHECKCODE not between", value1, value2, "checkcode");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(String value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(String value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(String value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(String value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(String value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(String value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLike(String value) {
            addCriterion("AMT like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotLike(String value) {
            addCriterion("AMT not like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<String> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<String> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(String value1, String value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(String value1, String value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeIsNull() {
            addCriterion("NOTESKINDCODE is null");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeIsNotNull() {
            addCriterion("NOTESKINDCODE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeEqualTo(String value) {
            addCriterion("NOTESKINDCODE =", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotEqualTo(String value) {
            addCriterion("NOTESKINDCODE <>", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeGreaterThan(String value) {
            addCriterion("NOTESKINDCODE >", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTESKINDCODE >=", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeLessThan(String value) {
            addCriterion("NOTESKINDCODE <", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeLessThanOrEqualTo(String value) {
            addCriterion("NOTESKINDCODE <=", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeLike(String value) {
            addCriterion("NOTESKINDCODE like", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotLike(String value) {
            addCriterion("NOTESKINDCODE not like", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeIn(List<String> values) {
            addCriterion("NOTESKINDCODE in", values, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotIn(List<String> values) {
            addCriterion("NOTESKINDCODE not in", values, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeBetween(String value1, String value2) {
            addCriterion("NOTESKINDCODE between", value1, value2, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotBetween(String value1, String value2) {
            addCriterion("NOTESKINDCODE not between", value1, value2, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameIsNull() {
            addCriterion("NOTESKINDNAME is null");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameIsNotNull() {
            addCriterion("NOTESKINDNAME is not null");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameEqualTo(String value) {
            addCriterion("NOTESKINDNAME =", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameNotEqualTo(String value) {
            addCriterion("NOTESKINDNAME <>", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameGreaterThan(String value) {
            addCriterion("NOTESKINDNAME >", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameGreaterThanOrEqualTo(String value) {
            addCriterion("NOTESKINDNAME >=", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameLessThan(String value) {
            addCriterion("NOTESKINDNAME <", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameLessThanOrEqualTo(String value) {
            addCriterion("NOTESKINDNAME <=", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameLike(String value) {
            addCriterion("NOTESKINDNAME like", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameNotLike(String value) {
            addCriterion("NOTESKINDNAME not like", value, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameIn(List<String> values) {
            addCriterion("NOTESKINDNAME in", values, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameNotIn(List<String> values) {
            addCriterion("NOTESKINDNAME not in", values, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameBetween(String value1, String value2) {
            addCriterion("NOTESKINDNAME between", value1, value2, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andNoteskindnameNotBetween(String value1, String value2) {
            addCriterion("NOTESKINDNAME not between", value1, value2, "noteskindname");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeIsNull() {
            addCriterion("AGENTBANKCODE is null");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeIsNotNull() {
            addCriterion("AGENTBANKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeEqualTo(String value) {
            addCriterion("AGENTBANKCODE =", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotEqualTo(String value) {
            addCriterion("AGENTBANKCODE <>", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeGreaterThan(String value) {
            addCriterion("AGENTBANKCODE >", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("AGENTBANKCODE >=", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeLessThan(String value) {
            addCriterion("AGENTBANKCODE <", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeLessThanOrEqualTo(String value) {
            addCriterion("AGENTBANKCODE <=", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeLike(String value) {
            addCriterion("AGENTBANKCODE like", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotLike(String value) {
            addCriterion("AGENTBANKCODE not like", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeIn(List<String> values) {
            addCriterion("AGENTBANKCODE in", values, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotIn(List<String> values) {
            addCriterion("AGENTBANKCODE not in", values, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeBetween(String value1, String value2) {
            addCriterion("AGENTBANKCODE between", value1, value2, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotBetween(String value1, String value2) {
            addCriterion("AGENTBANKCODE not between", value1, value2, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameIsNull() {
            addCriterion("AGENTBANKNAME is null");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameIsNotNull() {
            addCriterion("AGENTBANKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameEqualTo(String value) {
            addCriterion("AGENTBANKNAME =", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotEqualTo(String value) {
            addCriterion("AGENTBANKNAME <>", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameGreaterThan(String value) {
            addCriterion("AGENTBANKNAME >", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameGreaterThanOrEqualTo(String value) {
            addCriterion("AGENTBANKNAME >=", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameLessThan(String value) {
            addCriterion("AGENTBANKNAME <", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameLessThanOrEqualTo(String value) {
            addCriterion("AGENTBANKNAME <=", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameLike(String value) {
            addCriterion("AGENTBANKNAME like", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotLike(String value) {
            addCriterion("AGENTBANKNAME not like", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameIn(List<String> values) {
            addCriterion("AGENTBANKNAME in", values, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotIn(List<String> values) {
            addCriterion("AGENTBANKNAME not in", values, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameBetween(String value1, String value2) {
            addCriterion("AGENTBANKNAME between", value1, value2, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotBetween(String value1, String value2) {
            addCriterion("AGENTBANKNAME not between", value1, value2, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andBankrecdateIsNull() {
            addCriterion("BANKRECDATE is null");
            return (Criteria) this;
        }

        public Criteria andBankrecdateIsNotNull() {
            addCriterion("BANKRECDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankrecdateEqualTo(String value) {
            addCriterion("BANKRECDATE =", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotEqualTo(String value) {
            addCriterion("BANKRECDATE <>", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateGreaterThan(String value) {
            addCriterion("BANKRECDATE >", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateGreaterThanOrEqualTo(String value) {
            addCriterion("BANKRECDATE >=", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateLessThan(String value) {
            addCriterion("BANKRECDATE <", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateLessThanOrEqualTo(String value) {
            addCriterion("BANKRECDATE <=", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateLike(String value) {
            addCriterion("BANKRECDATE like", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotLike(String value) {
            addCriterion("BANKRECDATE not like", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateIn(List<String> values) {
            addCriterion("BANKRECDATE in", values, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotIn(List<String> values) {
            addCriterion("BANKRECDATE not in", values, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateBetween(String value1, String value2) {
            addCriterion("BANKRECDATE between", value1, value2, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotBetween(String value1, String value2) {
            addCriterion("BANKRECDATE not between", value1, value2, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateIsNull() {
            addCriterion("BANKACCTDATE is null");
            return (Criteria) this;
        }

        public Criteria andBankacctdateIsNotNull() {
            addCriterion("BANKACCTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankacctdateEqualTo(String value) {
            addCriterion("BANKACCTDATE =", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotEqualTo(String value) {
            addCriterion("BANKACCTDATE <>", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateGreaterThan(String value) {
            addCriterion("BANKACCTDATE >", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateGreaterThanOrEqualTo(String value) {
            addCriterion("BANKACCTDATE >=", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateLessThan(String value) {
            addCriterion("BANKACCTDATE <", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateLessThanOrEqualTo(String value) {
            addCriterion("BANKACCTDATE <=", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateLike(String value) {
            addCriterion("BANKACCTDATE like", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotLike(String value) {
            addCriterion("BANKACCTDATE not like", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateIn(List<String> values) {
            addCriterion("BANKACCTDATE in", values, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotIn(List<String> values) {
            addCriterion("BANKACCTDATE not in", values, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateBetween(String value1, String value2) {
            addCriterion("BANKACCTDATE between", value1, value2, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotBetween(String value1, String value2) {
            addCriterion("BANKACCTDATE not between", value1, value2, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andIspreauditIsNull() {
            addCriterion("ISPREAUDIT is null");
            return (Criteria) this;
        }

        public Criteria andIspreauditIsNotNull() {
            addCriterion("ISPREAUDIT is not null");
            return (Criteria) this;
        }

        public Criteria andIspreauditEqualTo(String value) {
            addCriterion("ISPREAUDIT =", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotEqualTo(String value) {
            addCriterion("ISPREAUDIT <>", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditGreaterThan(String value) {
            addCriterion("ISPREAUDIT >", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditGreaterThanOrEqualTo(String value) {
            addCriterion("ISPREAUDIT >=", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditLessThan(String value) {
            addCriterion("ISPREAUDIT <", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditLessThanOrEqualTo(String value) {
            addCriterion("ISPREAUDIT <=", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditLike(String value) {
            addCriterion("ISPREAUDIT like", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotLike(String value) {
            addCriterion("ISPREAUDIT not like", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditIn(List<String> values) {
            addCriterion("ISPREAUDIT in", values, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotIn(List<String> values) {
            addCriterion("ISPREAUDIT not in", values, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditBetween(String value1, String value2) {
            addCriterion("ISPREAUDIT between", value1, value2, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotBetween(String value1, String value2) {
            addCriterion("ISPREAUDIT not between", value1, value2, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIsNull() {
            addCriterion("RECFEEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIsNotNull() {
            addCriterion("RECFEEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagEqualTo(String value) {
            addCriterion("RECFEEFLAG =", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotEqualTo(String value) {
            addCriterion("RECFEEFLAG <>", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagGreaterThan(String value) {
            addCriterion("RECFEEFLAG >", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagGreaterThanOrEqualTo(String value) {
            addCriterion("RECFEEFLAG >=", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLessThan(String value) {
            addCriterion("RECFEEFLAG <", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLessThanOrEqualTo(String value) {
            addCriterion("RECFEEFLAG <=", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLike(String value) {
            addCriterion("RECFEEFLAG like", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotLike(String value) {
            addCriterion("RECFEEFLAG not like", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIn(List<String> values) {
            addCriterion("RECFEEFLAG in", values, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotIn(List<String> values) {
            addCriterion("RECFEEFLAG not in", values, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagBetween(String value1, String value2) {
            addCriterion("RECFEEFLAG between", value1, value2, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotBetween(String value1, String value2) {
            addCriterion("RECFEEFLAG not between", value1, value2, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andBilltypeIsNull() {
            addCriterion("BILLTYPE is null");
            return (Criteria) this;
        }

        public Criteria andBilltypeIsNotNull() {
            addCriterion("BILLTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBilltypeEqualTo(String value) {
            addCriterion("BILLTYPE =", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotEqualTo(String value) {
            addCriterion("BILLTYPE <>", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeGreaterThan(String value) {
            addCriterion("BILLTYPE >", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeGreaterThanOrEqualTo(String value) {
            addCriterion("BILLTYPE >=", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLessThan(String value) {
            addCriterion("BILLTYPE <", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLessThanOrEqualTo(String value) {
            addCriterion("BILLTYPE <=", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLike(String value) {
            addCriterion("BILLTYPE like", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotLike(String value) {
            addCriterion("BILLTYPE not like", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeIn(List<String> values) {
            addCriterion("BILLTYPE in", values, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotIn(List<String> values) {
            addCriterion("BILLTYPE not in", values, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeBetween(String value1, String value2) {
            addCriterion("BILLTYPE between", value1, value2, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotBetween(String value1, String value2) {
            addCriterion("BILLTYPE not between", value1, value2, "billtype");
            return (Criteria) this;
        }

        public Criteria andLatefeeIsNull() {
            addCriterion("LATEFEE is null");
            return (Criteria) this;
        }

        public Criteria andLatefeeIsNotNull() {
            addCriterion("LATEFEE is not null");
            return (Criteria) this;
        }

        public Criteria andLatefeeEqualTo(String value) {
            addCriterion("LATEFEE =", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotEqualTo(String value) {
            addCriterion("LATEFEE <>", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeGreaterThan(String value) {
            addCriterion("LATEFEE >", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeGreaterThanOrEqualTo(String value) {
            addCriterion("LATEFEE >=", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeLessThan(String value) {
            addCriterion("LATEFEE <", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeLessThanOrEqualTo(String value) {
            addCriterion("LATEFEE <=", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeLike(String value) {
            addCriterion("LATEFEE like", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotLike(String value) {
            addCriterion("LATEFEE not like", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeIn(List<String> values) {
            addCriterion("LATEFEE in", values, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotIn(List<String> values) {
            addCriterion("LATEFEE not in", values, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeBetween(String value1, String value2) {
            addCriterion("LATEFEE between", value1, value2, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotBetween(String value1, String value2) {
            addCriterion("LATEFEE not between", value1, value2, "latefee");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeIsNull() {
            addCriterion("BANKNOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeIsNotNull() {
            addCriterion("BANKNOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeEqualTo(String value) {
            addCriterion("BANKNOTESCODE =", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeNotEqualTo(String value) {
            addCriterion("BANKNOTESCODE <>", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeGreaterThan(String value) {
            addCriterion("BANKNOTESCODE >", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("BANKNOTESCODE >=", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeLessThan(String value) {
            addCriterion("BANKNOTESCODE <", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeLessThanOrEqualTo(String value) {
            addCriterion("BANKNOTESCODE <=", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeLike(String value) {
            addCriterion("BANKNOTESCODE like", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeNotLike(String value) {
            addCriterion("BANKNOTESCODE not like", value, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeIn(List<String> values) {
            addCriterion("BANKNOTESCODE in", values, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeNotIn(List<String> values) {
            addCriterion("BANKNOTESCODE not in", values, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeBetween(String value1, String value2) {
            addCriterion("BANKNOTESCODE between", value1, value2, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andBanknotescodeNotBetween(String value1, String value2) {
            addCriterion("BANKNOTESCODE not between", value1, value2, "banknotescode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeIsNull() {
            addCriterion("REFUNDAPPLYCODE is null");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeIsNotNull() {
            addCriterion("REFUNDAPPLYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE =", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE <>", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeGreaterThan(String value) {
            addCriterion("REFUNDAPPLYCODE >", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeGreaterThanOrEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE >=", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeLessThan(String value) {
            addCriterion("REFUNDAPPLYCODE <", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeLessThanOrEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE <=", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeLike(String value) {
            addCriterion("REFUNDAPPLYCODE like", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotLike(String value) {
            addCriterion("REFUNDAPPLYCODE not like", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeIn(List<String> values) {
            addCriterion("REFUNDAPPLYCODE in", values, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotIn(List<String> values) {
            addCriterion("REFUNDAPPLYCODE not in", values, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeBetween(String value1, String value2) {
            addCriterion("REFUNDAPPLYCODE between", value1, value2, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotBetween(String value1, String value2) {
            addCriterion("REFUNDAPPLYCODE not between", value1, value2, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeIsNull() {
            addCriterion("FROMNOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeIsNotNull() {
            addCriterion("FROMNOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeEqualTo(String value) {
            addCriterion("FROMNOTESCODE =", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotEqualTo(String value) {
            addCriterion("FROMNOTESCODE <>", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeGreaterThan(String value) {
            addCriterion("FROMNOTESCODE >", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("FROMNOTESCODE >=", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeLessThan(String value) {
            addCriterion("FROMNOTESCODE <", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeLessThanOrEqualTo(String value) {
            addCriterion("FROMNOTESCODE <=", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeLike(String value) {
            addCriterion("FROMNOTESCODE like", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotLike(String value) {
            addCriterion("FROMNOTESCODE not like", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeIn(List<String> values) {
            addCriterion("FROMNOTESCODE in", values, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotIn(List<String> values) {
            addCriterion("FROMNOTESCODE not in", values, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeBetween(String value1, String value2) {
            addCriterion("FROMNOTESCODE between", value1, value2, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotBetween(String value1, String value2) {
            addCriterion("FROMNOTESCODE not between", value1, value2, "fromnotescode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 22 09:46:09 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_ACT_TXN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}