package apps.fisjz.repository.model;

public class FsJzfBaseBdgagency {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.CODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.NAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.GUID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.LEVELNO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String levelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.SUPERCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String supercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ISLEAF
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.PERKINDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String perkindname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String fundsupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ELSEFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String elsefact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String mofdepname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ZIP
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.FAX
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.INDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String indname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.TEL
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPENAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String agencytypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String agencylevelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ORGCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ENTPRFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String entprfact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ENTPRPLAN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String entprplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ADMINFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String adminfact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.ADMINPLAN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String adminplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPECODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String agencytypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String mofdepcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.PERKINDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String perkindcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String fundsupcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String agencylevelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BDGAGENCY.INDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String indcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.CODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.CODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.CODE
     *
     * @param code the value for FIS.FS_JZF_BASE_BDGAGENCY.CODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.NAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.NAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.NAME
     *
     * @param name the value for FIS.FS_JZF_BASE_BDGAGENCY.NAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.GUID
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.GUID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.GUID
     *
     * @param guid the value for FIS.FS_JZF_BASE_BDGAGENCY.GUID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.LEVELNO
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.LEVELNO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.LEVELNO
     *
     * @param levelno the value for FIS.FS_JZF_BASE_BDGAGENCY.LEVELNO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setLevelno(String levelno) {
        this.levelno = levelno == null ? null : levelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.SUPERCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.SUPERCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getSupercode() {
        return supercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.SUPERCODE
     *
     * @param supercode the value for FIS.FS_JZF_BASE_BDGAGENCY.SUPERCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setSupercode(String supercode) {
        this.supercode = supercode == null ? null : supercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ISLEAF
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ISLEAF
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ISLEAF
     *
     * @param isleaf the value for FIS.FS_JZF_BASE_BDGAGENCY.ISLEAF
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.PERKINDNAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.PERKINDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getPerkindname() {
        return perkindname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.PERKINDNAME
     *
     * @param perkindname the value for FIS.FS_JZF_BASE_BDGAGENCY.PERKINDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setPerkindname(String perkindname) {
        this.perkindname = perkindname == null ? null : perkindname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPNAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getFundsupname() {
        return fundsupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPNAME
     *
     * @param fundsupname the value for FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setFundsupname(String fundsupname) {
        this.fundsupname = fundsupname == null ? null : fundsupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ELSEFACT
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ELSEFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getElsefact() {
        return elsefact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ELSEFACT
     *
     * @param elsefact the value for FIS.FS_JZF_BASE_BDGAGENCY.ELSEFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setElsefact(String elsefact) {
        this.elsefact = elsefact == null ? null : elsefact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPNAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getMofdepname() {
        return mofdepname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPNAME
     *
     * @param mofdepname the value for FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setMofdepname(String mofdepname) {
        this.mofdepname = mofdepname == null ? null : mofdepname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ZIP
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ZIP
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ZIP
     *
     * @param zip the value for FIS.FS_JZF_BASE_BDGAGENCY.ZIP
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.FAX
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.FAX
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.FAX
     *
     * @param fax the value for FIS.FS_JZF_BASE_BDGAGENCY.FAX
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.INDNAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.INDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getIndname() {
        return indname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.INDNAME
     *
     * @param indname the value for FIS.FS_JZF_BASE_BDGAGENCY.INDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setIndname(String indname) {
        this.indname = indname == null ? null : indname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.TEL
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.TEL
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.TEL
     *
     * @param tel the value for FIS.FS_JZF_BASE_BDGAGENCY.TEL
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPENAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPENAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAgencytypename() {
        return agencytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPENAME
     *
     * @param agencytypename the value for FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPENAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAgencytypename(String agencytypename) {
        this.agencytypename = agencytypename == null ? null : agencytypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELNAME
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAgencylevelname() {
        return agencylevelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELNAME
     *
     * @param agencylevelname the value for FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAgencylevelname(String agencylevelname) {
        this.agencylevelname = agencylevelname == null ? null : agencylevelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ORGCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ORGCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ORGCODE
     *
     * @param orgcode the value for FIS.FS_JZF_BASE_BDGAGENCY.ORGCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ENTPRFACT
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ENTPRFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getEntprfact() {
        return entprfact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ENTPRFACT
     *
     * @param entprfact the value for FIS.FS_JZF_BASE_BDGAGENCY.ENTPRFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setEntprfact(String entprfact) {
        this.entprfact = entprfact == null ? null : entprfact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ENTPRPLAN
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ENTPRPLAN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getEntprplan() {
        return entprplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ENTPRPLAN
     *
     * @param entprplan the value for FIS.FS_JZF_BASE_BDGAGENCY.ENTPRPLAN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setEntprplan(String entprplan) {
        this.entprplan = entprplan == null ? null : entprplan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ADMINFACT
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ADMINFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAdminfact() {
        return adminfact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ADMINFACT
     *
     * @param adminfact the value for FIS.FS_JZF_BASE_BDGAGENCY.ADMINFACT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAdminfact(String adminfact) {
        this.adminfact = adminfact == null ? null : adminfact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ADMINPLAN
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.ADMINPLAN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAdminplan() {
        return adminplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.ADMINPLAN
     *
     * @param adminplan the value for FIS.FS_JZF_BASE_BDGAGENCY.ADMINPLAN
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAdminplan(String adminplan) {
        this.adminplan = adminplan == null ? null : adminplan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPECODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPECODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAgencytypecode() {
        return agencytypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPECODE
     *
     * @param agencytypecode the value for FIS.FS_JZF_BASE_BDGAGENCY.AGENCYTYPECODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAgencytypecode(String agencytypecode) {
        this.agencytypecode = agencytypecode == null ? null : agencytypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getMofdepcode() {
        return mofdepcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPCODE
     *
     * @param mofdepcode the value for FIS.FS_JZF_BASE_BDGAGENCY.MOFDEPCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setMofdepcode(String mofdepcode) {
        this.mofdepcode = mofdepcode == null ? null : mofdepcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.PERKINDCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.PERKINDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getPerkindcode() {
        return perkindcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.PERKINDCODE
     *
     * @param perkindcode the value for FIS.FS_JZF_BASE_BDGAGENCY.PERKINDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setPerkindcode(String perkindcode) {
        this.perkindcode = perkindcode == null ? null : perkindcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getFundsupcode() {
        return fundsupcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPCODE
     *
     * @param fundsupcode the value for FIS.FS_JZF_BASE_BDGAGENCY.FUNDSUPCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setFundsupcode(String fundsupcode) {
        this.fundsupcode = fundsupcode == null ? null : fundsupcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAgencylevelcode() {
        return agencylevelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELCODE
     *
     * @param agencylevelcode the value for FIS.FS_JZF_BASE_BDGAGENCY.AGENCYLEVELCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAgencylevelcode(String agencylevelcode) {
        this.agencylevelcode = agencylevelcode == null ? null : agencylevelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.INDCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BDGAGENCY.INDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getIndcode() {
        return indcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BDGAGENCY.INDCODE
     *
     * @param indcode the value for FIS.FS_JZF_BASE_BDGAGENCY.INDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setIndcode(String indcode) {
        this.indcode = indcode == null ? null : indcode.trim();
    }
}