package apps.fisjz.repository.model;

public class FsJzfPaymentItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.BILLID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.MAINID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String mainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String nontaxprogramcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMNAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String nontaxprogramname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.UNITS
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.AMOUNT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String standardkindcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDNAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String standardkindname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.AMT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_ITEM.BANKNUM
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String banknum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.PKID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.PKID
     *
     * @param pkid the value for FIS.FS_JZF_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.BILLID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.BILLID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.BILLID
     *
     * @param billid the value for FIS.FS_JZF_PAYMENT_ITEM.BILLID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setBillid(String billid) {
        this.billid = billid == null ? null : billid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.MAINID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.MAINID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getMainid() {
        return mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.MAINID
     *
     * @param mainid the value for FIS.FS_JZF_PAYMENT_ITEM.MAINID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setMainid(String mainid) {
        this.mainid = mainid == null ? null : mainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getNontaxprogramcode() {
        return nontaxprogramcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMCODE
     *
     * @param nontaxprogramcode the value for FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setNontaxprogramcode(String nontaxprogramcode) {
        this.nontaxprogramcode = nontaxprogramcode == null ? null : nontaxprogramcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMNAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getNontaxprogramname() {
        return nontaxprogramname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMNAME
     *
     * @param nontaxprogramname the value for FIS.FS_JZF_PAYMENT_ITEM.NONTAXPROGRAMNAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setNontaxprogramname(String nontaxprogramname) {
        this.nontaxprogramname = nontaxprogramname == null ? null : nontaxprogramname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.UNITS
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.UNITS
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.UNITS
     *
     * @param units the value for FIS.FS_JZF_PAYMENT_ITEM.UNITS
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.AMOUNT
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.AMOUNT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.AMOUNT
     *
     * @param amount the value for FIS.FS_JZF_PAYMENT_ITEM.AMOUNT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getStandardkindcode() {
        return standardkindcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDCODE
     *
     * @param standardkindcode the value for FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setStandardkindcode(String standardkindcode) {
        this.standardkindcode = standardkindcode == null ? null : standardkindcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDNAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getStandardkindname() {
        return standardkindname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDNAME
     *
     * @param standardkindname the value for FIS.FS_JZF_PAYMENT_ITEM.STANDARDKINDNAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setStandardkindname(String standardkindname) {
        this.standardkindname = standardkindname == null ? null : standardkindname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.AMT
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.AMT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.AMT
     *
     * @param amt the value for FIS.FS_JZF_PAYMENT_ITEM.AMT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setAmt(String amt) {
        this.amt = amt == null ? null : amt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_ITEM.BANKNUM
     *
     * @return the value of FIS.FS_JZF_PAYMENT_ITEM.BANKNUM
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getBanknum() {
        return banknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_ITEM.BANKNUM
     *
     * @param banknum the value for FIS.FS_JZF_PAYMENT_ITEM.BANKNUM
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setBanknum(String banknum) {
        this.banknum = banknum == null ? null : banknum.trim();
    }
}