package apps.fisjz.repository.model;

public class FsJzfPaymentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PKID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.BILLID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String paynotescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.NOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String notescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.CHECKCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String checkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.AMT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.NOTESKINDCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String noteskindcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.NOTESKINKNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String noteskinkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String performdeptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String performdeptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PRINTDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String printdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.AGENTBANKCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String agentbankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.AGENTBANKNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String agentbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String payfeemethodcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String payfeemethodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYMETHODCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String paymethodcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYMETHODNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String paymethodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String payerbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.PAYERBANKACCT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String payerbankacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.CREATETIME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.BILLTYPE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String billtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.LATEFEE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String latefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.BANKNUM
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String banknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.CREATER
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.BANKRECDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String bankrecdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.BANKACCTDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String bankacctdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.ISPREAUDIT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String ispreaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.RECFEEFLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String recfeeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.FROMNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String fromnotescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String recusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERBANK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String recuserbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERBANKACCOUNT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String recuserbankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.REFUNDREASON
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String refundreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.BANKNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String banknotescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.REFUNDAPPLYCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String refundapplycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.TEXT1
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String text1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.TEXT2
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String text2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.TEXT3
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String text3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.OPER_BANKID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String operBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.OPER_ID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String hostBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String hostChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String fbBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    private String fbChkFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PKID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PKID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PKID
     *
     * @param pkid the value for FIS.FS_JZF_PAYMENT_INFO.PKID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.BILLID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.BILLID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.BILLID
     *
     * @param billid the value for FIS.FS_JZF_PAYMENT_INFO.BILLID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setBillid(String billid) {
        this.billid = billid == null ? null : billid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYNOTESCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPaynotescode() {
        return paynotescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYNOTESCODE
     *
     * @param paynotescode the value for FIS.FS_JZF_PAYMENT_INFO.PAYNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPaynotescode(String paynotescode) {
        this.paynotescode = paynotescode == null ? null : paynotescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.NOTESCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.NOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getNotescode() {
        return notescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.NOTESCODE
     *
     * @param notescode the value for FIS.FS_JZF_PAYMENT_INFO.NOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setNotescode(String notescode) {
        this.notescode = notescode == null ? null : notescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.CHECKCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.CHECKCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getCheckcode() {
        return checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.CHECKCODE
     *
     * @param checkcode the value for FIS.FS_JZF_PAYMENT_INFO.CHECKCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setCheckcode(String checkcode) {
        this.checkcode = checkcode == null ? null : checkcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.AMT
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.AMT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.AMT
     *
     * @param amt the value for FIS.FS_JZF_PAYMENT_INFO.AMT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setAmt(String amt) {
        this.amt = amt == null ? null : amt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.NOTESKINDCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.NOTESKINDCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getNoteskindcode() {
        return noteskindcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.NOTESKINDCODE
     *
     * @param noteskindcode the value for FIS.FS_JZF_PAYMENT_INFO.NOTESKINDCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setNoteskindcode(String noteskindcode) {
        this.noteskindcode = noteskindcode == null ? null : noteskindcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.NOTESKINKNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.NOTESKINKNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getNoteskinkname() {
        return noteskinkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.NOTESKINKNAME
     *
     * @param noteskinkname the value for FIS.FS_JZF_PAYMENT_INFO.NOTESKINKNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setNoteskinkname(String noteskinkname) {
        this.noteskinkname = noteskinkname == null ? null : noteskinkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPerformdeptcode() {
        return performdeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTCODE
     *
     * @param performdeptcode the value for FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPerformdeptcode(String performdeptcode) {
        this.performdeptcode = performdeptcode == null ? null : performdeptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPerformdeptname() {
        return performdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTNAME
     *
     * @param performdeptname the value for FIS.FS_JZF_PAYMENT_INFO.PERFORMDEPTNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPerformdeptname(String performdeptname) {
        this.performdeptname = performdeptname == null ? null : performdeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PRINTDATE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PRINTDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPrintdate() {
        return printdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PRINTDATE
     *
     * @param printdate the value for FIS.FS_JZF_PAYMENT_INFO.PRINTDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPrintdate(String printdate) {
        this.printdate = printdate == null ? null : printdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.AGENTBANKCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.AGENTBANKCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getAgentbankcode() {
        return agentbankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.AGENTBANKCODE
     *
     * @param agentbankcode the value for FIS.FS_JZF_PAYMENT_INFO.AGENTBANKCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setAgentbankcode(String agentbankcode) {
        this.agentbankcode = agentbankcode == null ? null : agentbankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.AGENTBANKNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.AGENTBANKNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getAgentbankname() {
        return agentbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.AGENTBANKNAME
     *
     * @param agentbankname the value for FIS.FS_JZF_PAYMENT_INFO.AGENTBANKNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setAgentbankname(String agentbankname) {
        this.agentbankname = agentbankname == null ? null : agentbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPayfeemethodcode() {
        return payfeemethodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODCODE
     *
     * @param payfeemethodcode the value for FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPayfeemethodcode(String payfeemethodcode) {
        this.payfeemethodcode = payfeemethodcode == null ? null : payfeemethodcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPayfeemethodname() {
        return payfeemethodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODNAME
     *
     * @param payfeemethodname the value for FIS.FS_JZF_PAYMENT_INFO.PAYFEEMETHODNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPayfeemethodname(String payfeemethodname) {
        this.payfeemethodname = payfeemethodname == null ? null : payfeemethodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYMETHODCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYMETHODCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPaymethodcode() {
        return paymethodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYMETHODCODE
     *
     * @param paymethodcode the value for FIS.FS_JZF_PAYMENT_INFO.PAYMETHODCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPaymethodcode(String paymethodcode) {
        this.paymethodcode = paymethodcode == null ? null : paymethodcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYMETHODNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYMETHODNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPaymethodname() {
        return paymethodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYMETHODNAME
     *
     * @param paymethodname the value for FIS.FS_JZF_PAYMENT_INFO.PAYMETHODNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPaymethodname(String paymethodname) {
        this.paymethodname = paymethodname == null ? null : paymethodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYER
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYER
     *
     * @param payer the value for FIS.FS_JZF_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYERBANK
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPayerbank() {
        return payerbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYERBANK
     *
     * @param payerbank the value for FIS.FS_JZF_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPayerbank(String payerbank) {
        this.payerbank = payerbank == null ? null : payerbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYERBANKACCT
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.PAYERBANKACCT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getPayerbankacct() {
        return payerbankacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.PAYERBANKACCT
     *
     * @param payerbankacct the value for FIS.FS_JZF_PAYMENT_INFO.PAYERBANKACCT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setPayerbankacct(String payerbankacct) {
        this.payerbankacct = payerbankacct == null ? null : payerbankacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.REMARK
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.REMARK
     *
     * @param remark the value for FIS.FS_JZF_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.CREATETIME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.CREATETIME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.CREATETIME
     *
     * @param createtime the value for FIS.FS_JZF_PAYMENT_INFO.CREATETIME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.BILLTYPE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.BILLTYPE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.BILLTYPE
     *
     * @param billtype the value for FIS.FS_JZF_PAYMENT_INFO.BILLTYPE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setBilltype(String billtype) {
        this.billtype = billtype == null ? null : billtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.LATEFEE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.LATEFEE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getLatefee() {
        return latefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.LATEFEE
     *
     * @param latefee the value for FIS.FS_JZF_PAYMENT_INFO.LATEFEE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setLatefee(String latefee) {
        this.latefee = latefee == null ? null : latefee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKNUM
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.BANKNUM
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getBanknum() {
        return banknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKNUM
     *
     * @param banknum the value for FIS.FS_JZF_PAYMENT_INFO.BANKNUM
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setBanknum(String banknum) {
        this.banknum = banknum == null ? null : banknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.CREATER
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.CREATER
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.CREATER
     *
     * @param creater the value for FIS.FS_JZF_PAYMENT_INFO.CREATER
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKRECDATE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.BANKRECDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getBankrecdate() {
        return bankrecdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKRECDATE
     *
     * @param bankrecdate the value for FIS.FS_JZF_PAYMENT_INFO.BANKRECDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setBankrecdate(String bankrecdate) {
        this.bankrecdate = bankrecdate == null ? null : bankrecdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKACCTDATE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.BANKACCTDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getBankacctdate() {
        return bankacctdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKACCTDATE
     *
     * @param bankacctdate the value for FIS.FS_JZF_PAYMENT_INFO.BANKACCTDATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setBankacctdate(String bankacctdate) {
        this.bankacctdate = bankacctdate == null ? null : bankacctdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.ISPREAUDIT
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.ISPREAUDIT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getIspreaudit() {
        return ispreaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.ISPREAUDIT
     *
     * @param ispreaudit the value for FIS.FS_JZF_PAYMENT_INFO.ISPREAUDIT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setIspreaudit(String ispreaudit) {
        this.ispreaudit = ispreaudit == null ? null : ispreaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECFEEFLAG
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.RECFEEFLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRecfeeflag() {
        return recfeeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECFEEFLAG
     *
     * @param recfeeflag the value for FIS.FS_JZF_PAYMENT_INFO.RECFEEFLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRecfeeflag(String recfeeflag) {
        this.recfeeflag = recfeeflag == null ? null : recfeeflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.FROMNOTESCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.FROMNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getFromnotescode() {
        return fromnotescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.FROMNOTESCODE
     *
     * @param fromnotescode the value for FIS.FS_JZF_PAYMENT_INFO.FROMNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setFromnotescode(String fromnotescode) {
        this.fromnotescode = fromnotescode == null ? null : fromnotescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERNAME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.RECUSERNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRecusername() {
        return recusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERNAME
     *
     * @param recusername the value for FIS.FS_JZF_PAYMENT_INFO.RECUSERNAME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRecusername(String recusername) {
        this.recusername = recusername == null ? null : recusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERBANK
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.RECUSERBANK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRecuserbank() {
        return recuserbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERBANK
     *
     * @param recuserbank the value for FIS.FS_JZF_PAYMENT_INFO.RECUSERBANK
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRecuserbank(String recuserbank) {
        this.recuserbank = recuserbank == null ? null : recuserbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERBANKACCOUNT
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.RECUSERBANKACCOUNT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRecuserbankaccount() {
        return recuserbankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.RECUSERBANKACCOUNT
     *
     * @param recuserbankaccount the value for FIS.FS_JZF_PAYMENT_INFO.RECUSERBANKACCOUNT
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRecuserbankaccount(String recuserbankaccount) {
        this.recuserbankaccount = recuserbankaccount == null ? null : recuserbankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.REFUNDREASON
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.REFUNDREASON
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRefundreason() {
        return refundreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.REFUNDREASON
     *
     * @param refundreason the value for FIS.FS_JZF_PAYMENT_INFO.REFUNDREASON
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRefundreason(String refundreason) {
        this.refundreason = refundreason == null ? null : refundreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKNOTESCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.BANKNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getBanknotescode() {
        return banknotescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.BANKNOTESCODE
     *
     * @param banknotescode the value for FIS.FS_JZF_PAYMENT_INFO.BANKNOTESCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setBanknotescode(String banknotescode) {
        this.banknotescode = banknotescode == null ? null : banknotescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.REFUNDAPPLYCODE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.REFUNDAPPLYCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getRefundapplycode() {
        return refundapplycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.REFUNDAPPLYCODE
     *
     * @param refundapplycode the value for FIS.FS_JZF_PAYMENT_INFO.REFUNDAPPLYCODE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setRefundapplycode(String refundapplycode) {
        this.refundapplycode = refundapplycode == null ? null : refundapplycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.TEXT1
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.TEXT1
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.TEXT1
     *
     * @param text1 the value for FIS.FS_JZF_PAYMENT_INFO.TEXT1
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.TEXT2
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.TEXT2
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.TEXT2
     *
     * @param text2 the value for FIS.FS_JZF_PAYMENT_INFO.TEXT2
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.TEXT3
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.TEXT3
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getText3() {
        return text3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.TEXT3
     *
     * @param text3 the value for FIS.FS_JZF_PAYMENT_INFO.TEXT3
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setText3(String text3) {
        this.text3 = text3 == null ? null : text3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_BANKID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.OPER_BANKID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getOperBankid() {
        return operBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_BANKID
     *
     * @param operBankid the value for FIS.FS_JZF_PAYMENT_INFO.OPER_BANKID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setOperBankid(String operBankid) {
        this.operBankid = operBankid == null ? null : operBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_ID
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.OPER_ID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_ID
     *
     * @param operId the value for FIS.FS_JZF_PAYMENT_INFO.OPER_ID
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_DATE
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_DATE
     *
     * @param operDate the value for FIS.FS_JZF_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_TIME
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.OPER_TIME
     *
     * @param operTime the value for FIS.FS_JZF_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getHostBookFlag() {
        return hostBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @param hostBookFlag the value for FIS.FS_JZF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setHostBookFlag(String hostBookFlag) {
        this.hostBookFlag = hostBookFlag == null ? null : hostBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getHostChkFlag() {
        return hostChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @param hostChkFlag the value for FIS.FS_JZF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setHostChkFlag(String hostChkFlag) {
        this.hostChkFlag = hostChkFlag == null ? null : hostChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getFbBookFlag() {
        return fbBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @param fbBookFlag the value for FIS.FS_JZF_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setFbBookFlag(String fbBookFlag) {
        this.fbBookFlag = fbBookFlag == null ? null : fbBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @return the value of FIS.FS_JZF_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public String getFbChkFlag() {
        return fbChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @param fbChkFlag the value for FIS.FS_JZF_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Mon Sep 23 11:18:50 CST 2013
     */
    public void setFbChkFlag(String fbChkFlag) {
        this.fbChkFlag = fbChkFlag == null ? null : fbChkFlag.trim();
    }
}