package apps.fisjz.repository.model;

public class FsJzfActTxn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.PKID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.BANKNUM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String banknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.BILLID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.PAYNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String paynotescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.NOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String notescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.CHECKCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String checkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.AMT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.NOTESKINDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String noteskindcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.NOTESKINDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String noteskindname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.AGENTBANKCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String agentbankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.AGENTBANKNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String agentbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.BANKRECDATE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String bankrecdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.BANKACCTDATE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String bankacctdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.ISPREAUDIT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String ispreaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.RECFEEFLAG
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String recfeeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.BILLTYPE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String billtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.LATEFEE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String latefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.BANKNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String banknotescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.REFUNDAPPLYCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String refundapplycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_ACT_TXN.FROMNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String fromnotescode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.PKID
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.PKID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.PKID
     *
     * @param pkid the value for FIS.FS_JZF_ACT_TXN.PKID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.BANKNUM
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.BANKNUM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getBanknum() {
        return banknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.BANKNUM
     *
     * @param banknum the value for FIS.FS_JZF_ACT_TXN.BANKNUM
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setBanknum(String banknum) {
        this.banknum = banknum == null ? null : banknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.BILLID
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.BILLID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.BILLID
     *
     * @param billid the value for FIS.FS_JZF_ACT_TXN.BILLID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setBillid(String billid) {
        this.billid = billid == null ? null : billid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.PAYNOTESCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.PAYNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getPaynotescode() {
        return paynotescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.PAYNOTESCODE
     *
     * @param paynotescode the value for FIS.FS_JZF_ACT_TXN.PAYNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setPaynotescode(String paynotescode) {
        this.paynotescode = paynotescode == null ? null : paynotescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.NOTESCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.NOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getNotescode() {
        return notescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.NOTESCODE
     *
     * @param notescode the value for FIS.FS_JZF_ACT_TXN.NOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setNotescode(String notescode) {
        this.notescode = notescode == null ? null : notescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.CHECKCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.CHECKCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getCheckcode() {
        return checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.CHECKCODE
     *
     * @param checkcode the value for FIS.FS_JZF_ACT_TXN.CHECKCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setCheckcode(String checkcode) {
        this.checkcode = checkcode == null ? null : checkcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.AMT
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.AMT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.AMT
     *
     * @param amt the value for FIS.FS_JZF_ACT_TXN.AMT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAmt(String amt) {
        this.amt = amt == null ? null : amt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.NOTESKINDCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.NOTESKINDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getNoteskindcode() {
        return noteskindcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.NOTESKINDCODE
     *
     * @param noteskindcode the value for FIS.FS_JZF_ACT_TXN.NOTESKINDCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setNoteskindcode(String noteskindcode) {
        this.noteskindcode = noteskindcode == null ? null : noteskindcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.NOTESKINDNAME
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.NOTESKINDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getNoteskindname() {
        return noteskindname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.NOTESKINDNAME
     *
     * @param noteskindname the value for FIS.FS_JZF_ACT_TXN.NOTESKINDNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setNoteskindname(String noteskindname) {
        this.noteskindname = noteskindname == null ? null : noteskindname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.AGENTBANKCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.AGENTBANKCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAgentbankcode() {
        return agentbankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.AGENTBANKCODE
     *
     * @param agentbankcode the value for FIS.FS_JZF_ACT_TXN.AGENTBANKCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAgentbankcode(String agentbankcode) {
        this.agentbankcode = agentbankcode == null ? null : agentbankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.AGENTBANKNAME
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.AGENTBANKNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getAgentbankname() {
        return agentbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.AGENTBANKNAME
     *
     * @param agentbankname the value for FIS.FS_JZF_ACT_TXN.AGENTBANKNAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setAgentbankname(String agentbankname) {
        this.agentbankname = agentbankname == null ? null : agentbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.BANKRECDATE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.BANKRECDATE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getBankrecdate() {
        return bankrecdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.BANKRECDATE
     *
     * @param bankrecdate the value for FIS.FS_JZF_ACT_TXN.BANKRECDATE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setBankrecdate(String bankrecdate) {
        this.bankrecdate = bankrecdate == null ? null : bankrecdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.BANKACCTDATE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.BANKACCTDATE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getBankacctdate() {
        return bankacctdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.BANKACCTDATE
     *
     * @param bankacctdate the value for FIS.FS_JZF_ACT_TXN.BANKACCTDATE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setBankacctdate(String bankacctdate) {
        this.bankacctdate = bankacctdate == null ? null : bankacctdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.ISPREAUDIT
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.ISPREAUDIT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getIspreaudit() {
        return ispreaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.ISPREAUDIT
     *
     * @param ispreaudit the value for FIS.FS_JZF_ACT_TXN.ISPREAUDIT
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setIspreaudit(String ispreaudit) {
        this.ispreaudit = ispreaudit == null ? null : ispreaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.RECFEEFLAG
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.RECFEEFLAG
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getRecfeeflag() {
        return recfeeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.RECFEEFLAG
     *
     * @param recfeeflag the value for FIS.FS_JZF_ACT_TXN.RECFEEFLAG
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setRecfeeflag(String recfeeflag) {
        this.recfeeflag = recfeeflag == null ? null : recfeeflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.BILLTYPE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.BILLTYPE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.BILLTYPE
     *
     * @param billtype the value for FIS.FS_JZF_ACT_TXN.BILLTYPE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setBilltype(String billtype) {
        this.billtype = billtype == null ? null : billtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.LATEFEE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.LATEFEE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getLatefee() {
        return latefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.LATEFEE
     *
     * @param latefee the value for FIS.FS_JZF_ACT_TXN.LATEFEE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setLatefee(String latefee) {
        this.latefee = latefee == null ? null : latefee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.BANKNOTESCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.BANKNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getBanknotescode() {
        return banknotescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.BANKNOTESCODE
     *
     * @param banknotescode the value for FIS.FS_JZF_ACT_TXN.BANKNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setBanknotescode(String banknotescode) {
        this.banknotescode = banknotescode == null ? null : banknotescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.REFUNDAPPLYCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.REFUNDAPPLYCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getRefundapplycode() {
        return refundapplycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.REFUNDAPPLYCODE
     *
     * @param refundapplycode the value for FIS.FS_JZF_ACT_TXN.REFUNDAPPLYCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setRefundapplycode(String refundapplycode) {
        this.refundapplycode = refundapplycode == null ? null : refundapplycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_ACT_TXN.FROMNOTESCODE
     *
     * @return the value of FIS.FS_JZF_ACT_TXN.FROMNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getFromnotescode() {
        return fromnotescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_ACT_TXN.FROMNOTESCODE
     *
     * @param fromnotescode the value for FIS.FS_JZF_ACT_TXN.FROMNOTESCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setFromnotescode(String fromnotescode) {
        this.fromnotescode = fromnotescode == null ? null : fromnotescode.trim();
    }
}