package apps.fisjz.repository.model;

import java.util.ArrayList;
import java.util.List;

public class FsJzfPaymentInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public FsJzfPaymentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillidIsNull() {
            addCriterion("BILLID is null");
            return (Criteria) this;
        }

        public Criteria andBillidIsNotNull() {
            addCriterion("BILLID is not null");
            return (Criteria) this;
        }

        public Criteria andBillidEqualTo(String value) {
            addCriterion("BILLID =", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotEqualTo(String value) {
            addCriterion("BILLID <>", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThan(String value) {
            addCriterion("BILLID >", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThanOrEqualTo(String value) {
            addCriterion("BILLID >=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThan(String value) {
            addCriterion("BILLID <", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThanOrEqualTo(String value) {
            addCriterion("BILLID <=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLike(String value) {
            addCriterion("BILLID like", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotLike(String value) {
            addCriterion("BILLID not like", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidIn(List<String> values) {
            addCriterion("BILLID in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotIn(List<String> values) {
            addCriterion("BILLID not in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidBetween(String value1, String value2) {
            addCriterion("BILLID between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotBetween(String value1, String value2) {
            addCriterion("BILLID not between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIsNull() {
            addCriterion("PAYNOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIsNotNull() {
            addCriterion("PAYNOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeEqualTo(String value) {
            addCriterion("PAYNOTESCODE =", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotEqualTo(String value) {
            addCriterion("PAYNOTESCODE <>", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeGreaterThan(String value) {
            addCriterion("PAYNOTESCODE >", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYNOTESCODE >=", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLessThan(String value) {
            addCriterion("PAYNOTESCODE <", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLessThanOrEqualTo(String value) {
            addCriterion("PAYNOTESCODE <=", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLike(String value) {
            addCriterion("PAYNOTESCODE like", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotLike(String value) {
            addCriterion("PAYNOTESCODE not like", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIn(List<String> values) {
            addCriterion("PAYNOTESCODE in", values, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotIn(List<String> values) {
            addCriterion("PAYNOTESCODE not in", values, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeBetween(String value1, String value2) {
            addCriterion("PAYNOTESCODE between", value1, value2, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotBetween(String value1, String value2) {
            addCriterion("PAYNOTESCODE not between", value1, value2, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeIsNull() {
            addCriterion("NOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andNotescodeIsNotNull() {
            addCriterion("NOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andNotescodeEqualTo(String value) {
            addCriterion("NOTESCODE =", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotEqualTo(String value) {
            addCriterion("NOTESCODE <>", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeGreaterThan(String value) {
            addCriterion("NOTESCODE >", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTESCODE >=", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeLessThan(String value) {
            addCriterion("NOTESCODE <", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeLessThanOrEqualTo(String value) {
            addCriterion("NOTESCODE <=", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeLike(String value) {
            addCriterion("NOTESCODE like", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotLike(String value) {
            addCriterion("NOTESCODE not like", value, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeIn(List<String> values) {
            addCriterion("NOTESCODE in", values, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotIn(List<String> values) {
            addCriterion("NOTESCODE not in", values, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeBetween(String value1, String value2) {
            addCriterion("NOTESCODE between", value1, value2, "notescode");
            return (Criteria) this;
        }

        public Criteria andNotescodeNotBetween(String value1, String value2) {
            addCriterion("NOTESCODE not between", value1, value2, "notescode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIsNull() {
            addCriterion("CHECKCODE is null");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIsNotNull() {
            addCriterion("CHECKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckcodeEqualTo(String value) {
            addCriterion("CHECKCODE =", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotEqualTo(String value) {
            addCriterion("CHECKCODE <>", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeGreaterThan(String value) {
            addCriterion("CHECKCODE >", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKCODE >=", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLessThan(String value) {
            addCriterion("CHECKCODE <", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLessThanOrEqualTo(String value) {
            addCriterion("CHECKCODE <=", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLike(String value) {
            addCriterion("CHECKCODE like", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotLike(String value) {
            addCriterion("CHECKCODE not like", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIn(List<String> values) {
            addCriterion("CHECKCODE in", values, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotIn(List<String> values) {
            addCriterion("CHECKCODE not in", values, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeBetween(String value1, String value2) {
            addCriterion("CHECKCODE between", value1, value2, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotBetween(String value1, String value2) {
            addCriterion("CHECKCODE not between", value1, value2, "checkcode");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(String value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(String value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(String value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(String value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(String value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(String value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLike(String value) {
            addCriterion("AMT like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotLike(String value) {
            addCriterion("AMT not like", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<String> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<String> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(String value1, String value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(String value1, String value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeIsNull() {
            addCriterion("NOTESKINDCODE is null");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeIsNotNull() {
            addCriterion("NOTESKINDCODE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeEqualTo(String value) {
            addCriterion("NOTESKINDCODE =", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotEqualTo(String value) {
            addCriterion("NOTESKINDCODE <>", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeGreaterThan(String value) {
            addCriterion("NOTESKINDCODE >", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTESKINDCODE >=", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeLessThan(String value) {
            addCriterion("NOTESKINDCODE <", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeLessThanOrEqualTo(String value) {
            addCriterion("NOTESKINDCODE <=", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeLike(String value) {
            addCriterion("NOTESKINDCODE like", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotLike(String value) {
            addCriterion("NOTESKINDCODE not like", value, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeIn(List<String> values) {
            addCriterion("NOTESKINDCODE in", values, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotIn(List<String> values) {
            addCriterion("NOTESKINDCODE not in", values, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeBetween(String value1, String value2) {
            addCriterion("NOTESKINDCODE between", value1, value2, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskindcodeNotBetween(String value1, String value2) {
            addCriterion("NOTESKINDCODE not between", value1, value2, "noteskindcode");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameIsNull() {
            addCriterion("NOTESKINKNAME is null");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameIsNotNull() {
            addCriterion("NOTESKINKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameEqualTo(String value) {
            addCriterion("NOTESKINKNAME =", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameNotEqualTo(String value) {
            addCriterion("NOTESKINKNAME <>", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameGreaterThan(String value) {
            addCriterion("NOTESKINKNAME >", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameGreaterThanOrEqualTo(String value) {
            addCriterion("NOTESKINKNAME >=", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameLessThan(String value) {
            addCriterion("NOTESKINKNAME <", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameLessThanOrEqualTo(String value) {
            addCriterion("NOTESKINKNAME <=", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameLike(String value) {
            addCriterion("NOTESKINKNAME like", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameNotLike(String value) {
            addCriterion("NOTESKINKNAME not like", value, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameIn(List<String> values) {
            addCriterion("NOTESKINKNAME in", values, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameNotIn(List<String> values) {
            addCriterion("NOTESKINKNAME not in", values, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameBetween(String value1, String value2) {
            addCriterion("NOTESKINKNAME between", value1, value2, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andNoteskinknameNotBetween(String value1, String value2) {
            addCriterion("NOTESKINKNAME not between", value1, value2, "noteskinkname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeIsNull() {
            addCriterion("PERFORMDEPTCODE is null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeIsNotNull() {
            addCriterion("PERFORMDEPTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeEqualTo(String value) {
            addCriterion("PERFORMDEPTCODE =", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeNotEqualTo(String value) {
            addCriterion("PERFORMDEPTCODE <>", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeGreaterThan(String value) {
            addCriterion("PERFORMDEPTCODE >", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PERFORMDEPTCODE >=", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeLessThan(String value) {
            addCriterion("PERFORMDEPTCODE <", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeLessThanOrEqualTo(String value) {
            addCriterion("PERFORMDEPTCODE <=", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeLike(String value) {
            addCriterion("PERFORMDEPTCODE like", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeNotLike(String value) {
            addCriterion("PERFORMDEPTCODE not like", value, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeIn(List<String> values) {
            addCriterion("PERFORMDEPTCODE in", values, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeNotIn(List<String> values) {
            addCriterion("PERFORMDEPTCODE not in", values, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeBetween(String value1, String value2) {
            addCriterion("PERFORMDEPTCODE between", value1, value2, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptcodeNotBetween(String value1, String value2) {
            addCriterion("PERFORMDEPTCODE not between", value1, value2, "performdeptcode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameIsNull() {
            addCriterion("PERFORMDEPTNAME is null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameIsNotNull() {
            addCriterion("PERFORMDEPTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameEqualTo(String value) {
            addCriterion("PERFORMDEPTNAME =", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameNotEqualTo(String value) {
            addCriterion("PERFORMDEPTNAME <>", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameGreaterThan(String value) {
            addCriterion("PERFORMDEPTNAME >", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameGreaterThanOrEqualTo(String value) {
            addCriterion("PERFORMDEPTNAME >=", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameLessThan(String value) {
            addCriterion("PERFORMDEPTNAME <", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameLessThanOrEqualTo(String value) {
            addCriterion("PERFORMDEPTNAME <=", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameLike(String value) {
            addCriterion("PERFORMDEPTNAME like", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameNotLike(String value) {
            addCriterion("PERFORMDEPTNAME not like", value, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameIn(List<String> values) {
            addCriterion("PERFORMDEPTNAME in", values, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameNotIn(List<String> values) {
            addCriterion("PERFORMDEPTNAME not in", values, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameBetween(String value1, String value2) {
            addCriterion("PERFORMDEPTNAME between", value1, value2, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPerformdeptnameNotBetween(String value1, String value2) {
            addCriterion("PERFORMDEPTNAME not between", value1, value2, "performdeptname");
            return (Criteria) this;
        }

        public Criteria andPrintdateIsNull() {
            addCriterion("PRINTDATE is null");
            return (Criteria) this;
        }

        public Criteria andPrintdateIsNotNull() {
            addCriterion("PRINTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPrintdateEqualTo(String value) {
            addCriterion("PRINTDATE =", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotEqualTo(String value) {
            addCriterion("PRINTDATE <>", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateGreaterThan(String value) {
            addCriterion("PRINTDATE >", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateGreaterThanOrEqualTo(String value) {
            addCriterion("PRINTDATE >=", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateLessThan(String value) {
            addCriterion("PRINTDATE <", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateLessThanOrEqualTo(String value) {
            addCriterion("PRINTDATE <=", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateLike(String value) {
            addCriterion("PRINTDATE like", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotLike(String value) {
            addCriterion("PRINTDATE not like", value, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateIn(List<String> values) {
            addCriterion("PRINTDATE in", values, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotIn(List<String> values) {
            addCriterion("PRINTDATE not in", values, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateBetween(String value1, String value2) {
            addCriterion("PRINTDATE between", value1, value2, "printdate");
            return (Criteria) this;
        }

        public Criteria andPrintdateNotBetween(String value1, String value2) {
            addCriterion("PRINTDATE not between", value1, value2, "printdate");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeIsNull() {
            addCriterion("AGENTBANKCODE is null");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeIsNotNull() {
            addCriterion("AGENTBANKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeEqualTo(String value) {
            addCriterion("AGENTBANKCODE =", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotEqualTo(String value) {
            addCriterion("AGENTBANKCODE <>", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeGreaterThan(String value) {
            addCriterion("AGENTBANKCODE >", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("AGENTBANKCODE >=", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeLessThan(String value) {
            addCriterion("AGENTBANKCODE <", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeLessThanOrEqualTo(String value) {
            addCriterion("AGENTBANKCODE <=", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeLike(String value) {
            addCriterion("AGENTBANKCODE like", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotLike(String value) {
            addCriterion("AGENTBANKCODE not like", value, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeIn(List<String> values) {
            addCriterion("AGENTBANKCODE in", values, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotIn(List<String> values) {
            addCriterion("AGENTBANKCODE not in", values, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeBetween(String value1, String value2) {
            addCriterion("AGENTBANKCODE between", value1, value2, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbankcodeNotBetween(String value1, String value2) {
            addCriterion("AGENTBANKCODE not between", value1, value2, "agentbankcode");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameIsNull() {
            addCriterion("AGENTBANKNAME is null");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameIsNotNull() {
            addCriterion("AGENTBANKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameEqualTo(String value) {
            addCriterion("AGENTBANKNAME =", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotEqualTo(String value) {
            addCriterion("AGENTBANKNAME <>", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameGreaterThan(String value) {
            addCriterion("AGENTBANKNAME >", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameGreaterThanOrEqualTo(String value) {
            addCriterion("AGENTBANKNAME >=", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameLessThan(String value) {
            addCriterion("AGENTBANKNAME <", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameLessThanOrEqualTo(String value) {
            addCriterion("AGENTBANKNAME <=", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameLike(String value) {
            addCriterion("AGENTBANKNAME like", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotLike(String value) {
            addCriterion("AGENTBANKNAME not like", value, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameIn(List<String> values) {
            addCriterion("AGENTBANKNAME in", values, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotIn(List<String> values) {
            addCriterion("AGENTBANKNAME not in", values, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameBetween(String value1, String value2) {
            addCriterion("AGENTBANKNAME between", value1, value2, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andAgentbanknameNotBetween(String value1, String value2) {
            addCriterion("AGENTBANKNAME not between", value1, value2, "agentbankname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeIsNull() {
            addCriterion("PAYFEEMETHODCODE is null");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeIsNotNull() {
            addCriterion("PAYFEEMETHODCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeEqualTo(String value) {
            addCriterion("PAYFEEMETHODCODE =", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeNotEqualTo(String value) {
            addCriterion("PAYFEEMETHODCODE <>", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeGreaterThan(String value) {
            addCriterion("PAYFEEMETHODCODE >", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYFEEMETHODCODE >=", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeLessThan(String value) {
            addCriterion("PAYFEEMETHODCODE <", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeLessThanOrEqualTo(String value) {
            addCriterion("PAYFEEMETHODCODE <=", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeLike(String value) {
            addCriterion("PAYFEEMETHODCODE like", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeNotLike(String value) {
            addCriterion("PAYFEEMETHODCODE not like", value, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeIn(List<String> values) {
            addCriterion("PAYFEEMETHODCODE in", values, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeNotIn(List<String> values) {
            addCriterion("PAYFEEMETHODCODE not in", values, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeBetween(String value1, String value2) {
            addCriterion("PAYFEEMETHODCODE between", value1, value2, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodcodeNotBetween(String value1, String value2) {
            addCriterion("PAYFEEMETHODCODE not between", value1, value2, "payfeemethodcode");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameIsNull() {
            addCriterion("PAYFEEMETHODNAME is null");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameIsNotNull() {
            addCriterion("PAYFEEMETHODNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameEqualTo(String value) {
            addCriterion("PAYFEEMETHODNAME =", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameNotEqualTo(String value) {
            addCriterion("PAYFEEMETHODNAME <>", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameGreaterThan(String value) {
            addCriterion("PAYFEEMETHODNAME >", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYFEEMETHODNAME >=", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameLessThan(String value) {
            addCriterion("PAYFEEMETHODNAME <", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameLessThanOrEqualTo(String value) {
            addCriterion("PAYFEEMETHODNAME <=", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameLike(String value) {
            addCriterion("PAYFEEMETHODNAME like", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameNotLike(String value) {
            addCriterion("PAYFEEMETHODNAME not like", value, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameIn(List<String> values) {
            addCriterion("PAYFEEMETHODNAME in", values, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameNotIn(List<String> values) {
            addCriterion("PAYFEEMETHODNAME not in", values, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameBetween(String value1, String value2) {
            addCriterion("PAYFEEMETHODNAME between", value1, value2, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPayfeemethodnameNotBetween(String value1, String value2) {
            addCriterion("PAYFEEMETHODNAME not between", value1, value2, "payfeemethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeIsNull() {
            addCriterion("PAYMETHODCODE is null");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeIsNotNull() {
            addCriterion("PAYMETHODCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeEqualTo(String value) {
            addCriterion("PAYMETHODCODE =", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeNotEqualTo(String value) {
            addCriterion("PAYMETHODCODE <>", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeGreaterThan(String value) {
            addCriterion("PAYMETHODCODE >", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMETHODCODE >=", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeLessThan(String value) {
            addCriterion("PAYMETHODCODE <", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeLessThanOrEqualTo(String value) {
            addCriterion("PAYMETHODCODE <=", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeLike(String value) {
            addCriterion("PAYMETHODCODE like", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeNotLike(String value) {
            addCriterion("PAYMETHODCODE not like", value, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeIn(List<String> values) {
            addCriterion("PAYMETHODCODE in", values, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeNotIn(List<String> values) {
            addCriterion("PAYMETHODCODE not in", values, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeBetween(String value1, String value2) {
            addCriterion("PAYMETHODCODE between", value1, value2, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodcodeNotBetween(String value1, String value2) {
            addCriterion("PAYMETHODCODE not between", value1, value2, "paymethodcode");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameIsNull() {
            addCriterion("PAYMETHODNAME is null");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameIsNotNull() {
            addCriterion("PAYMETHODNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameEqualTo(String value) {
            addCriterion("PAYMETHODNAME =", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameNotEqualTo(String value) {
            addCriterion("PAYMETHODNAME <>", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameGreaterThan(String value) {
            addCriterion("PAYMETHODNAME >", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMETHODNAME >=", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameLessThan(String value) {
            addCriterion("PAYMETHODNAME <", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameLessThanOrEqualTo(String value) {
            addCriterion("PAYMETHODNAME <=", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameLike(String value) {
            addCriterion("PAYMETHODNAME like", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameNotLike(String value) {
            addCriterion("PAYMETHODNAME not like", value, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameIn(List<String> values) {
            addCriterion("PAYMETHODNAME in", values, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameNotIn(List<String> values) {
            addCriterion("PAYMETHODNAME not in", values, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameBetween(String value1, String value2) {
            addCriterion("PAYMETHODNAME between", value1, value2, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPaymethodnameNotBetween(String value1, String value2) {
            addCriterion("PAYMETHODNAME not between", value1, value2, "paymethodname");
            return (Criteria) this;
        }

        public Criteria andPayerIsNull() {
            addCriterion("PAYER is null");
            return (Criteria) this;
        }

        public Criteria andPayerIsNotNull() {
            addCriterion("PAYER is not null");
            return (Criteria) this;
        }

        public Criteria andPayerEqualTo(String value) {
            addCriterion("PAYER =", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotEqualTo(String value) {
            addCriterion("PAYER <>", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerGreaterThan(String value) {
            addCriterion("PAYER >", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerGreaterThanOrEqualTo(String value) {
            addCriterion("PAYER >=", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerLessThan(String value) {
            addCriterion("PAYER <", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerLessThanOrEqualTo(String value) {
            addCriterion("PAYER <=", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerLike(String value) {
            addCriterion("PAYER like", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotLike(String value) {
            addCriterion("PAYER not like", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerIn(List<String> values) {
            addCriterion("PAYER in", values, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotIn(List<String> values) {
            addCriterion("PAYER not in", values, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerBetween(String value1, String value2) {
            addCriterion("PAYER between", value1, value2, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotBetween(String value1, String value2) {
            addCriterion("PAYER not between", value1, value2, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerbankIsNull() {
            addCriterion("PAYERBANK is null");
            return (Criteria) this;
        }

        public Criteria andPayerbankIsNotNull() {
            addCriterion("PAYERBANK is not null");
            return (Criteria) this;
        }

        public Criteria andPayerbankEqualTo(String value) {
            addCriterion("PAYERBANK =", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankNotEqualTo(String value) {
            addCriterion("PAYERBANK <>", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankGreaterThan(String value) {
            addCriterion("PAYERBANK >", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankGreaterThanOrEqualTo(String value) {
            addCriterion("PAYERBANK >=", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankLessThan(String value) {
            addCriterion("PAYERBANK <", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankLessThanOrEqualTo(String value) {
            addCriterion("PAYERBANK <=", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankLike(String value) {
            addCriterion("PAYERBANK like", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankNotLike(String value) {
            addCriterion("PAYERBANK not like", value, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankIn(List<String> values) {
            addCriterion("PAYERBANK in", values, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankNotIn(List<String> values) {
            addCriterion("PAYERBANK not in", values, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankBetween(String value1, String value2) {
            addCriterion("PAYERBANK between", value1, value2, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankNotBetween(String value1, String value2) {
            addCriterion("PAYERBANK not between", value1, value2, "payerbank");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctIsNull() {
            addCriterion("PAYERBANKACCT is null");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctIsNotNull() {
            addCriterion("PAYERBANKACCT is not null");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctEqualTo(String value) {
            addCriterion("PAYERBANKACCT =", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctNotEqualTo(String value) {
            addCriterion("PAYERBANKACCT <>", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctGreaterThan(String value) {
            addCriterion("PAYERBANKACCT >", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctGreaterThanOrEqualTo(String value) {
            addCriterion("PAYERBANKACCT >=", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctLessThan(String value) {
            addCriterion("PAYERBANKACCT <", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctLessThanOrEqualTo(String value) {
            addCriterion("PAYERBANKACCT <=", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctLike(String value) {
            addCriterion("PAYERBANKACCT like", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctNotLike(String value) {
            addCriterion("PAYERBANKACCT not like", value, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctIn(List<String> values) {
            addCriterion("PAYERBANKACCT in", values, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctNotIn(List<String> values) {
            addCriterion("PAYERBANKACCT not in", values, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctBetween(String value1, String value2) {
            addCriterion("PAYERBANKACCT between", value1, value2, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andPayerbankacctNotBetween(String value1, String value2) {
            addCriterion("PAYERBANKACCT not between", value1, value2, "payerbankacct");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("CREATETIME like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("CREATETIME not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andBilltypeIsNull() {
            addCriterion("BILLTYPE is null");
            return (Criteria) this;
        }

        public Criteria andBilltypeIsNotNull() {
            addCriterion("BILLTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBilltypeEqualTo(String value) {
            addCriterion("BILLTYPE =", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotEqualTo(String value) {
            addCriterion("BILLTYPE <>", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeGreaterThan(String value) {
            addCriterion("BILLTYPE >", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeGreaterThanOrEqualTo(String value) {
            addCriterion("BILLTYPE >=", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLessThan(String value) {
            addCriterion("BILLTYPE <", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLessThanOrEqualTo(String value) {
            addCriterion("BILLTYPE <=", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLike(String value) {
            addCriterion("BILLTYPE like", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotLike(String value) {
            addCriterion("BILLTYPE not like", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeIn(List<String> values) {
            addCriterion("BILLTYPE in", values, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotIn(List<String> values) {
            addCriterion("BILLTYPE not in", values, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeBetween(String value1, String value2) {
            addCriterion("BILLTYPE between", value1, value2, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotBetween(String value1, String value2) {
            addCriterion("BILLTYPE not between", value1, value2, "billtype");
            return (Criteria) this;
        }

        public Criteria andLatefeeIsNull() {
            addCriterion("LATEFEE is null");
            return (Criteria) this;
        }

        public Criteria andLatefeeIsNotNull() {
            addCriterion("LATEFEE is not null");
            return (Criteria) this;
        }

        public Criteria andLatefeeEqualTo(String value) {
            addCriterion("LATEFEE =", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotEqualTo(String value) {
            addCriterion("LATEFEE <>", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeGreaterThan(String value) {
            addCriterion("LATEFEE >", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeGreaterThanOrEqualTo(String value) {
            addCriterion("LATEFEE >=", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeLessThan(String value) {
            addCriterion("LATEFEE <", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeLessThanOrEqualTo(String value) {
            addCriterion("LATEFEE <=", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeLike(String value) {
            addCriterion("LATEFEE like", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotLike(String value) {
            addCriterion("LATEFEE not like", value, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeIn(List<String> values) {
            addCriterion("LATEFEE in", values, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotIn(List<String> values) {
            addCriterion("LATEFEE not in", values, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeBetween(String value1, String value2) {
            addCriterion("LATEFEE between", value1, value2, "latefee");
            return (Criteria) this;
        }

        public Criteria andLatefeeNotBetween(String value1, String value2) {
            addCriterion("LATEFEE not between", value1, value2, "latefee");
            return (Criteria) this;
        }

        public Criteria andBanknumIsNull() {
            addCriterion("BANKNUM is null");
            return (Criteria) this;
        }

        public Criteria andBanknumIsNotNull() {
            addCriterion("BANKNUM is not null");
            return (Criteria) this;
        }

        public Criteria andBanknumEqualTo(String value) {
            addCriterion("BANKNUM =", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotEqualTo(String value) {
            addCriterion("BANKNUM <>", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumGreaterThan(String value) {
            addCriterion("BANKNUM >", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumGreaterThanOrEqualTo(String value) {
            addCriterion("BANKNUM >=", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLessThan(String value) {
            addCriterion("BANKNUM <", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLessThanOrEqualTo(String value) {
            addCriterion("BANKNUM <=", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumLike(String value) {
            addCriterion("BANKNUM like", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotLike(String value) {
            addCriterion("BANKNUM not like", value, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumIn(List<String> values) {
            addCriterion("BANKNUM in", values, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotIn(List<String> values) {
            addCriterion("BANKNUM not in", values, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumBetween(String value1, String value2) {
            addCriterion("BANKNUM between", value1, value2, "banknum");
            return (Criteria) this;
        }

        public Criteria andBanknumNotBetween(String value1, String value2) {
            addCriterion("BANKNUM not between", value1, value2, "banknum");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("CREATER is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("CREATER is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("CREATER =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("CREATER <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("CREATER >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("CREATER >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("CREATER <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("CREATER <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("CREATER like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("CREATER not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("CREATER in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("CREATER not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("CREATER between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("CREATER not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andBankrecdateIsNull() {
            addCriterion("BANKRECDATE is null");
            return (Criteria) this;
        }

        public Criteria andBankrecdateIsNotNull() {
            addCriterion("BANKRECDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankrecdateEqualTo(String value) {
            addCriterion("BANKRECDATE =", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotEqualTo(String value) {
            addCriterion("BANKRECDATE <>", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateGreaterThan(String value) {
            addCriterion("BANKRECDATE >", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateGreaterThanOrEqualTo(String value) {
            addCriterion("BANKRECDATE >=", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateLessThan(String value) {
            addCriterion("BANKRECDATE <", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateLessThanOrEqualTo(String value) {
            addCriterion("BANKRECDATE <=", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateLike(String value) {
            addCriterion("BANKRECDATE like", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotLike(String value) {
            addCriterion("BANKRECDATE not like", value, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateIn(List<String> values) {
            addCriterion("BANKRECDATE in", values, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotIn(List<String> values) {
            addCriterion("BANKRECDATE not in", values, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateBetween(String value1, String value2) {
            addCriterion("BANKRECDATE between", value1, value2, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankrecdateNotBetween(String value1, String value2) {
            addCriterion("BANKRECDATE not between", value1, value2, "bankrecdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateIsNull() {
            addCriterion("BANKACCTDATE is null");
            return (Criteria) this;
        }

        public Criteria andBankacctdateIsNotNull() {
            addCriterion("BANKACCTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankacctdateEqualTo(String value) {
            addCriterion("BANKACCTDATE =", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotEqualTo(String value) {
            addCriterion("BANKACCTDATE <>", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateGreaterThan(String value) {
            addCriterion("BANKACCTDATE >", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateGreaterThanOrEqualTo(String value) {
            addCriterion("BANKACCTDATE >=", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateLessThan(String value) {
            addCriterion("BANKACCTDATE <", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateLessThanOrEqualTo(String value) {
            addCriterion("BANKACCTDATE <=", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateLike(String value) {
            addCriterion("BANKACCTDATE like", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotLike(String value) {
            addCriterion("BANKACCTDATE not like", value, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateIn(List<String> values) {
            addCriterion("BANKACCTDATE in", values, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotIn(List<String> values) {
            addCriterion("BANKACCTDATE not in", values, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateBetween(String value1, String value2) {
            addCriterion("BANKACCTDATE between", value1, value2, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andBankacctdateNotBetween(String value1, String value2) {
            addCriterion("BANKACCTDATE not between", value1, value2, "bankacctdate");
            return (Criteria) this;
        }

        public Criteria andIspreauditIsNull() {
            addCriterion("ISPREAUDIT is null");
            return (Criteria) this;
        }

        public Criteria andIspreauditIsNotNull() {
            addCriterion("ISPREAUDIT is not null");
            return (Criteria) this;
        }

        public Criteria andIspreauditEqualTo(String value) {
            addCriterion("ISPREAUDIT =", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotEqualTo(String value) {
            addCriterion("ISPREAUDIT <>", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditGreaterThan(String value) {
            addCriterion("ISPREAUDIT >", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditGreaterThanOrEqualTo(String value) {
            addCriterion("ISPREAUDIT >=", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditLessThan(String value) {
            addCriterion("ISPREAUDIT <", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditLessThanOrEqualTo(String value) {
            addCriterion("ISPREAUDIT <=", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditLike(String value) {
            addCriterion("ISPREAUDIT like", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotLike(String value) {
            addCriterion("ISPREAUDIT not like", value, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditIn(List<String> values) {
            addCriterion("ISPREAUDIT in", values, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotIn(List<String> values) {
            addCriterion("ISPREAUDIT not in", values, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditBetween(String value1, String value2) {
            addCriterion("ISPREAUDIT between", value1, value2, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andIspreauditNotBetween(String value1, String value2) {
            addCriterion("ISPREAUDIT not between", value1, value2, "ispreaudit");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIsNull() {
            addCriterion("RECFEEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIsNotNull() {
            addCriterion("RECFEEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagEqualTo(String value) {
            addCriterion("RECFEEFLAG =", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotEqualTo(String value) {
            addCriterion("RECFEEFLAG <>", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagGreaterThan(String value) {
            addCriterion("RECFEEFLAG >", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagGreaterThanOrEqualTo(String value) {
            addCriterion("RECFEEFLAG >=", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLessThan(String value) {
            addCriterion("RECFEEFLAG <", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLessThanOrEqualTo(String value) {
            addCriterion("RECFEEFLAG <=", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLike(String value) {
            addCriterion("RECFEEFLAG like", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotLike(String value) {
            addCriterion("RECFEEFLAG not like", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIn(List<String> values) {
            addCriterion("RECFEEFLAG in", values, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotIn(List<String> values) {
            addCriterion("RECFEEFLAG not in", values, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagBetween(String value1, String value2) {
            addCriterion("RECFEEFLAG between", value1, value2, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotBetween(String value1, String value2) {
            addCriterion("RECFEEFLAG not between", value1, value2, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeIsNull() {
            addCriterion("FROMNOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeIsNotNull() {
            addCriterion("FROMNOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeEqualTo(String value) {
            addCriterion("FROMNOTESCODE =", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotEqualTo(String value) {
            addCriterion("FROMNOTESCODE <>", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeGreaterThan(String value) {
            addCriterion("FROMNOTESCODE >", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("FROMNOTESCODE >=", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeLessThan(String value) {
            addCriterion("FROMNOTESCODE <", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeLessThanOrEqualTo(String value) {
            addCriterion("FROMNOTESCODE <=", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeLike(String value) {
            addCriterion("FROMNOTESCODE like", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotLike(String value) {
            addCriterion("FROMNOTESCODE not like", value, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeIn(List<String> values) {
            addCriterion("FROMNOTESCODE in", values, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotIn(List<String> values) {
            addCriterion("FROMNOTESCODE not in", values, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeBetween(String value1, String value2) {
            addCriterion("FROMNOTESCODE between", value1, value2, "fromnotescode");
            return (Criteria) this;
        }

        public Criteria andFromnotescodeNotBetween(String value1, String value2) {
            addCriterion("FROMNOTESCODE not between", value1, value2, "fromnotescode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 22 09:46:09 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_JZF_PAYMENT_INFO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}