package apps.fisjz.repository.model;

public class FsJzfBaseNontax {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.GUID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.NAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.LEVELNO
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String levelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.SUPERCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String supercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.ISLEAF
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.ISBNCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String isbncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_NONTAX.AREA_CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.GUID
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.GUID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.GUID
     *
     * @param guid the value for FIS.FS_JZF_BASE_NONTAX.GUID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.CODE
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.CODE
     *
     * @param code the value for FIS.FS_JZF_BASE_NONTAX.CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.NAME
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.NAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.NAME
     *
     * @param name the value for FIS.FS_JZF_BASE_NONTAX.NAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.LEVELNO
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.LEVELNO
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.LEVELNO
     *
     * @param levelno the value for FIS.FS_JZF_BASE_NONTAX.LEVELNO
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setLevelno(String levelno) {
        this.levelno = levelno == null ? null : levelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.SUPERCODE
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.SUPERCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getSupercode() {
        return supercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.SUPERCODE
     *
     * @param supercode the value for FIS.FS_JZF_BASE_NONTAX.SUPERCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setSupercode(String supercode) {
        this.supercode = supercode == null ? null : supercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.ISLEAF
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.ISLEAF
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.ISLEAF
     *
     * @param isleaf the value for FIS.FS_JZF_BASE_NONTAX.ISLEAF
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.ISBNCODE
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.ISBNCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getIsbncode() {
        return isbncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.ISBNCODE
     *
     * @param isbncode the value for FIS.FS_JZF_BASE_NONTAX.ISBNCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setIsbncode(String isbncode) {
        this.isbncode = isbncode == null ? null : isbncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_NONTAX.AREA_CODE
     *
     * @return the value of FIS.FS_JZF_BASE_NONTAX.AREA_CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_NONTAX.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_JZF_BASE_NONTAX.AREA_CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }
}