package apps.fisjz.repository.model;

public class FsJzfBaseFunc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.GUID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.CODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.NAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.SUPERCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String supercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.ISLEAF
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.LEVELNO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String levelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_FUNC.STARTTIME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    private String starttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.GUID
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.GUID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.GUID
     *
     * @param guid the value for FIS.FS_JZF_BASE_FUNC.GUID
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.CODE
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.CODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.CODE
     *
     * @param code the value for FIS.FS_JZF_BASE_FUNC.CODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.NAME
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.NAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.NAME
     *
     * @param name the value for FIS.FS_JZF_BASE_FUNC.NAME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.SUPERCODE
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.SUPERCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getSupercode() {
        return supercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.SUPERCODE
     *
     * @param supercode the value for FIS.FS_JZF_BASE_FUNC.SUPERCODE
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setSupercode(String supercode) {
        this.supercode = supercode == null ? null : supercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.ISLEAF
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.ISLEAF
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.ISLEAF
     *
     * @param isleaf the value for FIS.FS_JZF_BASE_FUNC.ISLEAF
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.LEVELNO
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.LEVELNO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.LEVELNO
     *
     * @param levelno the value for FIS.FS_JZF_BASE_FUNC.LEVELNO
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setLevelno(String levelno) {
        this.levelno = levelno == null ? null : levelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_FUNC.STARTTIME
     *
     * @return the value of FIS.FS_JZF_BASE_FUNC.STARTTIME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_FUNC.STARTTIME
     *
     * @param starttime the value for FIS.FS_JZF_BASE_FUNC.STARTTIME
     *
     * @mbggenerated Sun Sep 22 09:46:09 CST 2013
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }
}