package apps.fisjz.repository.model;

public class FsJzfBaseBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.GUID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.NAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.SUPERCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String supercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.ISLEAF
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.LEVELNO
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String levelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.STARTTIME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.ELSEFACT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String elsefact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_JZF_BASE_BANK.AREA_CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.GUID
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.GUID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.GUID
     *
     * @param guid the value for FIS.FS_JZF_BASE_BANK.GUID
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.CODE
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.CODE
     *
     * @param code the value for FIS.FS_JZF_BASE_BANK.CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.NAME
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.NAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.NAME
     *
     * @param name the value for FIS.FS_JZF_BASE_BANK.NAME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.SUPERCODE
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.SUPERCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getSupercode() {
        return supercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.SUPERCODE
     *
     * @param supercode the value for FIS.FS_JZF_BASE_BANK.SUPERCODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setSupercode(String supercode) {
        this.supercode = supercode == null ? null : supercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.ISLEAF
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.ISLEAF
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.ISLEAF
     *
     * @param isleaf the value for FIS.FS_JZF_BASE_BANK.ISLEAF
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.LEVELNO
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.LEVELNO
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.LEVELNO
     *
     * @param levelno the value for FIS.FS_JZF_BASE_BANK.LEVELNO
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setLevelno(String levelno) {
        this.levelno = levelno == null ? null : levelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.STARTTIME
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.STARTTIME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.STARTTIME
     *
     * @param starttime the value for FIS.FS_JZF_BASE_BANK.STARTTIME
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.ELSEFACT
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.ELSEFACT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getElsefact() {
        return elsefact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.ELSEFACT
     *
     * @param elsefact the value for FIS.FS_JZF_BASE_BANK.ELSEFACT
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setElsefact(String elsefact) {
        this.elsefact = elsefact == null ? null : elsefact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_JZF_BASE_BANK.AREA_CODE
     *
     * @return the value of FIS.FS_JZF_BASE_BANK.AREA_CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_JZF_BASE_BANK.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_JZF_BASE_BANK.AREA_CODE
     *
     * @mbggenerated Tue Sep 24 19:18:20 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }
}